### ISSUE TITLE
login not working

### ISSUE THREAD

**Issue by andredw2** [rconfig/rconfig#10]
hi, i installed this product now i can't login from the page, even creating a user in the database i can't. how can i solve? Thank you

**Comment by rconfig** [comment]
For clarity, rConfig professional is a product. rConfig core is free open source.

Please provide any relevant information when Submitting issues. Screenshots, logs etc...

**Comment by andredw2** [comment]
in the installation procedure a user is not indicated to login [https://ibb.co/7QXpvMg](url)

**Comment by rconfig** [comment]
Thanks. It's in the docs. But will add here for clarity

admin@domain.com
admin

**Comment by andredw2** [comment]
thank you :D it works
