### ISSUE TITLE
SHH related issue

### ISSUE THREAD

**Issue by cemkur** [rconfig/rconfig#102]
Hi there,
My issue is a bit specific. I am having a hard time grabbing SonicWALL configurations from some of the SonicWALL devices.  The issue is related to cipher and/or exchange methods when an ssh session is started. Configured jobs don't work, which leads me to investigate it from the VM that I used to run rConfig.  
Certain SonicWALL devices throw error on when an ssh session is initiated. While it differs on the local OS or the remote host, a simple example would be:

ssh 192.168.195.1
Unable to negotiate with 192.168.195.1 port 22: no matching key exchange method found. Their offer: diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1

I can fix this on the VM console by setting up a few parameters in ~/.ssh/config file, such as

================
Host 192.168.195.1
    KexAlgorithms +diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
    HostKeyAlgorithms=+ssh-rsa
    User admin
Host *
    Port 22
================

What I need to find out is how I can resolve this issue inside rConfig GUI.  I still get Access denied messages in the the logs for the failed connection attempts. 

Thank you
cem

**Comment by stephenstack** [comment]
Hi

The first thing about this issue, is the key exchange error that you are getting is from the OS. rConfig does not use the OSs SSH implementation to connect to devices. We use a native PHP library called PHPSECLIB. So, while the error you get from the OS SSH is legitimate (in that the sonicwall, is running legacy ciphers), this does not translate to rConfig. To see why rConfig cannot connect to and download a config from the device. Run the Debug command from the CLI. 
https://docs.rconfig.com/general/troubleshooting#rconfig-command-line-tools
https://www.youtube.com/watch?v=gu9yuvjvzUQ&t=515s

**Comment by stephenstack** [comment]
Any update or can we close this?

**Comment by cemkur** [comment]
Hi Stephen, sorry for the late reply. I was able to resolve the issue with your instructions, thank you very much.
