### ISSUE TITLE
Scheduled Tasks not working by selecting all Devices/Category/Tags

### ISSUE THREAD

**Issue by antoinechauvn** [rconfig/rconfig#111]
**Describe the bug**
Scheduled Tasks not working on all devices when all selected.

**To Reproduce**
1. Go to Scheduled Tasks
2. Add Category/ Devices or Tag
3. Run the Scheduled Task manually

**Expected behavior**
I have chosen my entire perimeter, but some equipment is not backed up (PANOS and FORTIGATE).

**Screenshots**
![image](https://github.com/rconfig/rconfig/assets/83721477/5ae1b313-4e2f-47d9-ad1b-5581ccae3289)
![image](https://github.com/rconfig/rconfig/assets/83721477/6715418e-eaec-43d8-93fd-81e657ad1280)

**rConfig Version Information (You can copy this from the rConfig dashboard):**
OS VERSION
Red Hat Enterprise 8.8 (Ootpa)
PHP / LARAVEL VERSION
8.3.3 / 10.44.0
REDIS VERSION
5.0.3
MYSQL VERSION
10.3.39

**Logs info (can be retrieved from /var/www/html/rconfig6/storage/logs - try to paste relevant logs only)
No relevant log to show

**Additional context**
Tested on Category / On all devices and by choosing all Tags.

**Comment by stephenstack** [comment]
Hi,
 
Apologies, we did not respond sooner to this. It is still an issue? Please follow the steps in this document for more troubleshooting information. 
https://docs.rconfig.com/general/troubleshooting/

**Comment by antoinechauvn** [comment]
Hello Stephen,


The problem is still there, but worse still, other problems are recurring (in particular a problem with SMTP which sends the email 5 times).

Would it be possible to set up a meeting about this?

Also, do you have any news about the problem with the Palo Alto that I told you about?

Regards,

**Comment by stephenstack** [comment]
Resolved with PR #114
