### ISSUE TITLE
Extreme - Failed config download

### ISSUE THREAD

**Issue by alessandroleva** [rconfig/rconfig#119]
**Describe the bug**

We cannot download the configuration of the Extreme Switches. If I manually download the configuration, it works, but it takes much time (10 minutes). We have a recurrent schedule every 3 h. I check with debug and when the debug is on, I do not detect any problems.

**To Reproduce**
1. Go to '.Latest downloads'
2. Click on 'View configuration'
4. See error: 

"{ "data": { "success": false, "message": "No config file found" }, "status": 422, "statusText": "", "headers": { "access-control-allow-headers": "Content-Type, Accept, Authorization, X-Requested-With, Application", "access-control-allow-methods": "POST, GET, OPTIONS, PUT, DELETE", "access-control-allow-origin": "", "cache-control": "no-cache, private", "content-type": "application/json", "date": "Thu, 20 Jun 2024 09:03:38 GMT", "server": "Apache/2.4.57 (Rocky Linux) OpenSSL/3.0.7", "strict-transport-security": "max-age=63072000", "x-powered-by": "PHP/8.2.13", "x-ratelimit-limit": "1000", "x-ratelimit-remaining": "987" }, "config": { "transitional": { "silentJSONParsing": true, "forcedJSONParsing": true, "clarifyTimeoutError": false }, "adapter": [ "xhr", "http" ], "transformRequest": [ null ], "transformResponse": [ null ], "timeout": 0, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1, "maxBodyLength": -1, "env": {}, "headers": { "Accept": "application/json, text/plain, */", "X-Requested-With": "XMLHttpRequest", "X-XSRF-TOKEN": "eyJpdiI6Im16YUQrdlJCZUxuQ0VkQTM3QnlyWUE9PSIsInZhbHVlIjoiWGV4QXRCMFZDb2JEVmwxbWltRmQ5NnpRRmUxZTFhZ05sSGN4emI1UktLcE44d0xqcVpEZ2s0UkIxcnR4U2R6eG43ejAxMVUxNjJmQkc0WklrYUZFQ0UrN0NVcVNiSVFLQWk4N25xMmlrSi9TOUwxT1pqdjRWb1RCcGJ1VWRJQ3MiLCJtYWMiOiJjMTRmYjFjMTg2MDFiNjgzNTkyYWI2YzMzYmE4YzY5NTg1MWQ5ZmExNTg2YWY5MWQwMTI2YThmNzFmNzAyODE2IiwidGFnIjoiIn0=" }, "method": "get", "url": "/api/configs/view-config/485224" }, "request": "[object XMLHttpRequest]" }"

**Expected behavior**
I expect to see the full configuration, but I see only "Loading file..."

**rConfig Version Information (You can copy this from the rConfig dashboard):**
OS VERSION
Rocky 9.3 (Blue Onyx)
PHP / LARAVEL VERSION
8.2.13 / 10.40.0
REDIS VERSION
6.2.7
MYSQL VERSION
10.5.22 

**Logs info (can be retrieved from /var/www/html/rconfig6/storage/logs - try to paste relevant logs only)

2024-06-20 11:01:24 App\Jobs\DownloadConfigNow ..................... RUNNING
  2024-06-20 11:02:06 App\Jobs\DeviceDownloadJob ..................... 1m FAIL
  2024-06-20 11:02:06 App\Jobs\DeviceDownloadJob ..................... 1m FAIL
  2024-06-20 11:02:08 App\Jobs\DeviceDownloadJob ..................... RUNNING
  2024-06-20 11:02:07 App\Jobs\DeviceDownloadJob ..................... 1m FAIL
  2024-06-20 11:02:08 App\Jobs\DeviceDownloadJob ..................... RUNNING
  2024-06-20 11:02:11 App\Jobs\DeviceDownloadJob ..................... 3s DONE
  2024-06-20 11:02:11 App\Jobs\DeviceDownloadJob ..................... 3s DONE
  2024-06-20 11:02:14 App\Jobs\TaskReportJob ......................... RUNNING
  2024-06-20 11:02:17 App\Jobs\TaskReportJob ......................... 3s DONE
  2024-06-20 11:02:17 App\Jobs\TaskCompleteNotificationJob ........... RUNNING
  2024-06-20 11:02:17 App\Jobs\TaskCompleteNotificationJob ..... 219.97ms DONE
  2024-06-20 11:02:29 App\Jobs\DownloadConfigNow ..................... RUNNING
  2024-06-20 11:04:29 App\Jobs\DownloadConfigNow ..................... 2m FAIL

RUNNING are Cisco, Juniper, Huawei, Mikrotik routers; FAIL only Extreme switches

**Comment by stephenstack** [comment]
Please read this doc. Especially the last section. Run the debug and paste the output here. (make sure it is sanitised)

https://docs.rconfig.com/general/troubleshooting/

cd /var/www/html/rconfig7/current && php artisan rconfig:download-device 1001 -d

This output will tell us what is going on

**Comment by alessandroleva** [comment]
Hello,

When we activate the DEBUG and then start the manual download, we can clearly see the configuration. The problem is when we try to schedule a massive download of the Extreme switches. Everytime the schedule starts, we cannot download any configuraiton.

The error we receive is the following:

"App\Jobs\DeviceDownloadJob has timed out. in /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/TimeoutExceededException.php:15"

We have already add more timeout in the yaml file - from 300 sec to 1000 sec-, but the result is the same.

Could you help us please?

Best regards

**Comment by alessandroleva** [comment]
Hello all,

Any news?

Best regards

**Comment by stephenstack** [comment]
It would be great to see the actual debug output. In that output there is a `Since last` value on each block. That tells us how long (in seconds) since the last action. Often the clear text output will tell us what the issue is. Increasing the timeout of the template, may not actually fix the issue. 

Please try to send the debug output to info@rconfig.com and we'll try to feedback on the exact issue.

**Comment by alessandroleva** [comment]
Hello Stehpen,

Thank for your feedback.

We will send an email to the address.

Best regards
