### ISSUE TITLE
Unable to download configuration using Web UI

### ISSUE THREAD

**Issue by ahill-itim** [rconfig/rconfig#120]
**Describe the bug**
I have added a device, Dell PowerConnect 5548, to rConfig V6 Core, however I am unable to download the config using the Web UI.

If I copy the debug CLI command I get this output:

CLI command:  cd /var/www/html/rconfig && php artisan rconfig:download-device 1 -d

Error: The stream or file "/var/www/html/rconfig/storage/logs/laravel-2024-07-09.log" could not be opened in append mode: Failed to open stream: Permission denied
  The exception occurred while attempting to log: chmod(): No such file or directory
  Context: {"exception":{}}

If I enter the CLI command below, it works perfectly:

 cd /var/www/html/rconfig && **sudo** php artisan rconfig:download-device 1 -d

Why do I need to add sudo to the php command for this to work? How can this be fixed so the sudo command isn't required?

Cheers,
Andy

**Comment by stephenstack** [comment]
Hi, 
When running this command, it will want to write the output to disk. Sudo/ root will allow that, your login user account likely will not. You should still see output on the terminal after you run the command, regardless of it saving the output to the disk or not, do you get any output on the terminal after running the command?

**Comment by ahill-itim** [comment]
Hi,
Yes there is output, it dumps the configuration from the show running-config command as expected and then errors with:

touch: cannot touch '/var/www/html/rconfig/storage/app/rconfig/data/Dell-Switches/PLYCORESWCL/2024/Jul/09/showrunning-config_1642.txt': Permission denied

In StreamHandler.php line 137:

  The stream or file "/var/www/html/rconfig/storage/logs/laravel-2024-07-09.log" could not be opened in append mode: Failed to open stream: Permission denied
  The exception occurred while attempting to log: chmod(): No such file or directory
  Context: {"exception":{}}

**Comment by ahill-itim** [comment]
Hi,
Any further thoughts on what might be happening here?

**Comment by stephenstack** [comment]
It would be ideal to see the full output for cd /var/www/html/rconfig && php artisan rconfig:download-device 1 -d

Thanks

**Comment by stephenstack** [comment]
any update on the full debug output. See how to do this here. 
https://docs.rconfig.com/general/troubleshooting/#rconfig-command-line-tools

I will close this in a couple of days in case of no feedback

**Comment by ahill-itim** [comment]
Ah yes, I have added the full output in the attached txt file.

Thank you.
[rconfigDebugOutput.txt](https://github.com/user-attachments/files/16493286/rconfigDebugOutput.txt)

**Comment by ahill-itim** [comment]
Hi, why has this been resolved, I have no fix from the full debug output posted 3 weeks ago now.
