### ISSUE TITLE
Backup of devices

### ISSUE THREAD

**Issue by andreamelis2020** [rconfig/rconfig#122]
Hello, when I try to backup Cisco switches, I notice that it gets stuck about halfway through the configuration.
The full configuration has 294 lines, while the configuration backup on rclient gets stuck at 169. I tried with more switches but I have the same problem.
Could you help me?
Thanks

**Comment by stephenstack** [comment]
hi
Check out this video and docs. Lets us know what you discover. 
https://www.youtube.com/watch?v=gu9yuvjvzUQ&list=PL8dpV2hQIDLRRMsYvVgZyzk3mCj3DNgBx&index=4
https://docs.rconfig.com/general/troubleshooting/#rconfig-command-line-tools

**Comment by andreamelis2020** [comment]
Thanks for the reply. I looked in the documents, did some tests but the problem remains.
I also tried to backup directly from cli, but it's still part of it.
I can't understand why.

presidiortr@ubuntu:/var/www/html/rconfig$ sudo php artisan rconfig:download-device 1 -d
Start rconfig:download-device IDs:1
b"""


.
.
.
!\r\n
interface FastEthernet0/48\r\n
 description #
""" // app/Http/Controllers/Connections/Telnet/Read.php:60
"#" // app/Http/Controllers/Connections/Telnet/Read.php:60
"#" // app/Http/Controllers/Connections/Telnet/Read.php:60
"# TRUNK TO 166 CED 2 #" // app/Http/Controllers/Connections/Telnet/Read.php:60
"# TRUNK TO 166 CED 2 #" // app/Http/Controllers/Connections/Telnet/Read.php:60
Start device download for ras166-switch-rolando ID:1
Config downloaded for ras166-switch-rolando with command: "show run" was successful
End rconfig:download-device

**Comment by stephenstack** [comment]
i wonder what the device prompt is set to for this device in the rConfig UI? is it just '#', or would it be the full prompt?
Check the template also, make sure Paging is set to 'on'

**Comment by andreamelis2020** [comment]
Thank you for your support.
This is the template I am using:

`# rConfig connection template - DO NOT EDIT DIRECTLY
## Notes: 
    ## Remember to update permissions for the templates folder after uploading new template files.
    ## run 'chown -R apache /home/rconfig' on your rconfig server CLI
    ## all items below that contain free text should be contained within quotation marks " "
    ## For new community submitted templates visit: https://github.com/rconfig/rConfig-templates

main:
  name: "Cisco IOS - TELNET - Enable"
  desc: "Cisco IOS TELNET based connection with enable mode"
connect:
  # connection timeout in seconds
  timeout: 30
  # type either telnet or ssh - must be in lowercase
  protocol: telnet
  # type port number for connection protocol choose from 1 - 65535
  port: 23
auth:
  # Set username name prompt. Must be in quotes. If left blank, username will not be sent.
  username: "Username:"
  # Set password name prompt. Must be in quotes
  password: "Password:"
  # Set enable mode on or off
  enable: on
  # set enable mode command. Must be in quotes
  enableCmd: "enable"
  # set enable mode password prompt. Must be in quotes
  enablePassPrmpt: "Password:"
  # set HP 'press any key' status. Is 'on' or 'off'
  hpAnyKeyStatus: off
  # set HP 'press any key' prompt. 
  hpAnyKeyPrmpt: "Press any key to continue"  
config:
    # Experimental: Some vendors use different linebreak settings. Choose 'n' (default) or 'r'
    linebreak: "n"
    # Disable config scrolling/ paging command. on/off
    paging: on
    # Disable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    pagingCmd: "terminal length 0"
    # re-enable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    resetPagingCmd: "terminal length 40"
    # Set pager prompt. Must place command in quotations
    pagerPrompt: "--More--"
    # Set pager prompt key-stroke. Must place command in quotations
    pagerPromptCmd: " "
    # Save configuration command. Leave blank, or set as required. Must be in quotes
    saveConfig: "wr mem"
    # Set exit command. Must place command in quotations
    exitCmd: "quit"`

![image](https://github.com/user-attachments/assets/c406c686-d6c1-420f-b5a8-83164bdacaed)
I tried to insert different cisco switches, but I still have the same problem, it fails to complete the backup.
I don't know what to feel anymore

**Comment by andreamelis2020** [comment]
Good morning, problem solved, I had to change the main prompt and enable prompt, putting the name of the device followed by # for the main and enable with >
![image](https://github.com/user-attachments/assets/30df8b4a-45dd-412d-8ab1-ba41064de618)
Thanks for the support

**Comment by stephenstack** [comment]
Beautiful! Well done. 

You are welcome to attend our upcoming webinars if you have some time in the coming weeks. 

https://lu.ma/user/usr-9PUZHkZ6tfltlEA
