### ISSUE TITLE
Can't connect to mariaDB server | Docker installation

### ISSUE THREAD

**Issue by hesham-ismail-sallam** [rconfig/rconfig#126]
I've followed all the steps in readme file in docker
but i get attached error that i can't connect to mariadb server with credentials in .env file
<img width="841" alt="image" src="https://github.com/user-attachments/assets/96338d0e-8a6c-4369-9da5-23b55cf43891">

**Comment by stephenstack** [comment]
You need to use a non ROOT user. Per the setup instructions, create a new user with privileges to the DB. Not only should you not use root, newer OS/ DB variant prohibit it. 

Thanks

**Comment by hesham-ismail-sallam** [comment]
I changed the user but still the same error
<img width="811" alt="image" src="https://github.com/user-attachments/assets/2e33f2af-1fc5-4bdd-ab8b-4bc9049df571">
<img width="832" alt="image" src="https://github.com/user-attachments/assets/68084ce7-1f0a-46c1-8474-e0e8c91294b0">

**Comment by stephenstack** [comment]
# Troubleshooting MySQL "Access Denied" Error During rConfig Setup

## Step 1: Verify MySQL Username and Password

1. **Check the credentials:**
   - Ensure the MySQL username and password provided during the rConfig setup are correct.
   - Test the credentials manually by logging in using the command line:

     ```bash
     mysql -u your_username -p
     ```
   - Enter the password when prompted. If you can log in, the credentials are correct. If not, you need to reset or correct them.

2. **Reset the MySQL password (if necessary):**
   - Log in to MySQL as the root user (or another user with sufficient privileges):

     ```bash
     sudo mysql -u root -p
     ```
   - Update the password:

     ```sql
     ALTER USER 'your_username'@'localhost' IDENTIFIED BY 'new_password';
     FLUSH PRIVILEGES;
     ```

3. **Verify the host:**
   - Ensure that the MySQL user is allowed to connect from the correct host. Typically, this is `localhost`, but if you're accessing the MySQL server from a remote machine, ensure the user has the correct permissions:

     ```sql
     SELECT host FROM mysql.user WHERE user = 'your_username';
     ```

   - If the user is not allowed to connect from the required host, grant the necessary privileges:

     ```sql
     GRANT ALL PRIVILEGES ON *.* TO 'your_username'@'your_host' IDENTIFIED BY 'your_password';
     FLUSH PRIVILEGES;
     ```

## Step 2: Check MySQL Server Status

1. **Ensure MySQL is running:**
   - Check if the MySQL server is running:

     ```bash
     sudo systemctl status mysql
     ```
   - If it's not running, start the MySQL service:

     ```bash
     sudo systemctl start mysql
     ```

2. **Check MySQL socket:**
   - Verify that the MySQL socket file exists and is correctly configured. The default location is `/var/run/mysqld/mysqld.sock`.
   - You can specify the correct socket path in your MySQL client configuration or during rConfig setup.

## Step 3: Review MySQL User Permissions

1. **Check user privileges:**
   - Ensure the MySQL user has sufficient privileges to create and manage the rConfig database and tables:

     ```sql
     SHOW GRANTS FOR 'your_username'@'your_host';
     ```

   - If necessary, grant the required permissions:

     ```sql
     GRANT ALL PRIVILEGES ON rconfig_db.* TO 'your_username'@'localhost';
     FLUSH PRIVILEGES;
     ```

## Step 4: Check MySQL Configuration Files

1. **Verify MySQL configuration:**
   - Ensure that the MySQL configuration file (`/etc/mysql/my.cnf` or `/etc/my.cnf`) is properly set up to allow connections from your rConfig server.

2. **Check bind-address:**
   - Ensure that the `bind-address` in the MySQL configuration file is set to `0.0.0.0` or the specific IP address you need:

     ```ini
     bind-address = 0.0.0.0
     ```

   - After making changes, restart MySQL:

     ```bash
     sudo systemctl restart mysql
     ```

## Step 5: Firewall and Security Group Configuration

1. **Check firewall rules:**
   - Ensure that the firewall on your MySQL server allows traffic on port 3306 (the default MySQL port).

     ```bash
     sudo ufw allow 3306/tcp
     ```

2. **Check cloud security groups (if applicable):**
   - If MySQL is hosted in a cloud environment (like AWS, GCP, or Azure), ensure the security group rules allow inbound traffic on port 3306 from your rConfig server's IP address.

## Step 6: Review Logs for Errors

1. **Check MySQL error log:**
   - Look at the MySQL error log for any detailed error messages that can give more context to the "access denied" issue.

**Comment by hesham-ismail-sallam** [comment]
I've tried all of these steps but i can't restart mysql service in mariadb container
but when i left the DB_Password = '' without password it works and i don't know how or why

**Comment by stephenstack** [comment]
Marking this resolved, thanks
