### ISSUE TITLE
SSO is not working

### ISSUE THREAD

**Issue by hesham-ismail-sallam** [rconfig/rconfig#127]
Hi,

I've installed rconfig v6 with docker and i've added parameters for SSO integration with Azure but the button didn't appear as it's expected in the documentation after doing  php artisan rconfig:clear-all 
<img width="518" alt="image" src="https://github.com/user-attachments/assets/099d025c-4609-4279-b745-d6fb86af578d">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/6b6a0ce1-9d07-4fa6-afcb-c68adaddc104">

**Comment by stephenstack** [comment]
Sorry, SSO is a Pro feature only

![image](https://github.com/user-attachments/assets/88120a52-433a-4c12-b3e3-1687e4e0dcca)
