### ISSUE TITLE
Rconfig6 os script

### ISSUE THREAD

**Issue by YellowJacket51** [rconfig/rconfig#130]
I am getting an error when trying to download the install script for v6. https://www.rconfig.com/downloads/rconfig6_ubuntu.sh is not found. Has the link changed or been taken offline?

**Comment by stephenstack** [comment]
Hi

This is a legacy script. Where did you get the URL for it? Please follow setups here for OS setup scripts.
https://docs.rconfig.com/getstarted/os-setup/#setup-scripts-by-os-type

**Comment by YellowJacket51** [comment]
Hi @stephenstack 

Thanks for reply. I see my issue now, I was under v6 specifically. My apologizes.

Thanks!
