### ISSUE TITLE
Server Version Reporting Incorrectly

### ISSUE THREAD

**Issue by br-amec** [rconfig/rconfig#134]
rConfig reporting the incorrect Server OS VERSION. Server OS Version installed is Ubuntu 24.04 LTS but reporting as Ubuntu 22.04.4 LTS

lsb_release -a shows
![image](https://github.com/user-attachments/assets/68c80741-e96e-47cc-992d-304d3c64e52c)

![image](https://github.com/user-attachments/assets/e0160452-3275-4c86-a206-e76f254c9b53)

**rConfig Version Information (You can copy this from the rConfig dashboard):**
OS VERSION
Ubuntu 22.04.4 LTS
PHP / LARAVEL VERSION
8.2.21 / 10.48.8
REDIS VERSION
7.2.5
MYSQL VERSION
10

**Comment by stephenstack** [comment]
Hi, We have captured this and added the fix to an upcoming release. keep and eye out, this next reelase is unreal :)

**Comment by br-amec** [comment]
@stephenstack You're awesome! Looking forward to the new release.
