### ISSUE TITLE
Scheduled Tasks Not Running

### ISSUE THREAD

**Issue by andmelis** [rconfig/rconfig#135]
**Describe the bug**
Hello, I have scheduled the task to backup every 5 minutes, click start, it starts but then it doesn't do it every 5 minutes. Do you know how I can fix it?

**Screenshots**
![immagine](https://github.com/user-attachments/assets/9e09c4ba-0114-408b-8ea7-f453094e6c2c)

**rConfig Version Information (You can copy this from the rConfig dashboard):**
OS VERSION
Ubuntu 24.04 LTS
PHP / LARAVEL VERSION
8.3.9 / 10.48.8
REDIS VERSION
7.0.15
MYSQL VERSION
10

**Comment by stephenstack** [comment]
Can you open the Queue Manager in settings, and send a screenshot of the dashboard?

**Comment by andmelis** [comment]
> Can you open the Queue Manager in settings, and send a screenshot of the dashboard?

![immagine](https://github.com/user-attachments/assets/93bcfb78-08b7-4a40-aaab-d30e8f5b896c)
could you tell me how to open the Queue configuration? Thanks

**Comment by stephenstack** [comment]
is there anything in completed or pending jobs? Also ,check if cron is setup
On the server CLI, login as root, and run
crontab -l

what is the output?

**Comment by andmelis** [comment]
I noticed that it gives me this message:
```
presidiortr@ubuntu:/var/www/html/rconfig$ php artisan schedule:work
  2024-10-22 11:18:00 Running ['artisan' rconfig:download-task 313739]  42ms FAIL
  ⇂ '/usr/bin/php8.3' 'artisan' rconfig:download-task 313739 >> 'storage/logs/laravel.log' 2>&1

```
When I click on start on "Scheduled Tasks", I noticed that it makes a backup of the device, then that's it, and I get this error.

![immagine](https://github.com/user-attachments/assets/0348cc1d-4324-49d5-bc7b-d4b8893a2033)

**Comment by andmelis** [comment]
> is there anything in completed or pending jobs? Also ,check if cron is setup On the server CLI, login as root, and run crontab -l
> 
> what is the output?

![immagine](https://github.com/user-attachments/assets/2b8d5576-2058-433d-b253-4b8dd4665180)

**Comment by stephenstack** [comment]
Seems the Cronjob is missing

Add the laravel Cron Job

crontab -e
Add the below, save and exit

    * * * * *  php /var/www/html/rconfig/artisan schedule:run >> /dev/null 2>&1

save and exit
verify cron with 'crontab -l'

**Comment by andmelis** [comment]
> Seems the Cronjob is missing
> 
> Add the laravel Cron Job
> 
> crontab -e Add the below, save and exit
> 
> ```
> * * * * *  php /var/www/html/rconfig/artisan schedule:run >> /dev/null 2>&1
> ```
> 
> save and exit verify cron with 'crontab -l'

could you tell me how to add it? Sorry but I'm not good with Ubuntu

**Comment by andmelis** [comment]
> Seems the Cronjob is missing
> 
> Add the laravel Cron Job
> 
> crontab -e Add the below, save and exit
> 
> ```
> * * * * *  php /var/www/html/rconfig/artisan schedule:run >> /dev/null 2>&1
> ```
> 
> save and exit verify cron with 'crontab -l'

I should have entered it

![immagine](https://github.com/user-attachments/assets/cda8d5e0-f40e-4b21-9654-7b46e9b80e97)

**Comment by stephenstack** [comment]
the php artisan install
should do it automatically. Re-read the setup instructions. Maybe you also missed toher steps

[php artisan install
z](https://github.com/rconfig/rconfig)

**Comment by andmelis** [comment]
Problem solved. Thank you very much
