### ISSUE TITLE
Config download of 48 port switch times out on GUI but not CLI

### ISSUE THREAD

**Issue by Wyatt-Black** [rconfig/rconfig#138]
**Describe the bug**
When attempting to download the configuration of a 48 port switch from the rconfig GUI, the job runs 5 times and times out after the fifth. On 24 port switches, the configs download as expected from the GUI with no issue. Running the CLI debug command: 
`cd /var/www/html/rconfig && php artisan rconfig:download-device 2 -d` downloads the configurations for 48 port switches with little hassle. 

**To Reproduce**
1. Go to 'Devices > Switch-03'
2. Click on 'Download Now'
3. Click on 'Notifications'
4. Job attempts 5 times and eventually errors out

**Expected behavior**
Clicking 'Download Now' on a 48 port switch should download the configs the same as a 24 port switch. 

**Screenshots**
![rconfig retries](https://github.com/user-attachments/assets/fc40b738-2799-4bcc-b5e2-22caed5da1a9)
![rconfig Horizon](https://github.com/user-attachments/assets/a02734da-195d-46cb-812f-a226f2114b33)

**rConfig Version Information (You can copy this from the rConfig dashboard):**
OS VERSION
Ubuntu 22.04.5 LTS
PHP / LARAVEL VERSION
8.3.13 / 10.48.22
REDIS VERSION
6.0.16
MYSQL VERSION
10

**Logs info**
[laravel-2024-11-20.log](https://github.com/user-attachments/files/17834186/laravel-2024-11-20.log)
[horizon.log](https://github.com/user-attachments/files/17834194/horizon.log)

**Additional context**
Failing device model: WS-CG3560G-48PS
Successful device model: WS-CG3560G-24PS
 
**Steps Taken**
Attempted to increase `HORIZON_PROD_TIMEOUT=` to 3600 seconds, and that only increased the duration of time between attempts.

**Comment by danielrConfig** [comment]
Hi there,

Thanks for sharing,

We would need to review the debug output (cd /var/www/html/rconfig && php artisan rconfig:download-device 2 -d). This will allow us to analyze the issue in greater detail.

Thanks,
Daniel B
rConfig

**Comment by Wyatt-Black** [comment]
Hello,

Below you will find the debug output as requested.

**Debug Logs**

**Comment by danielrConfig** [comment]
Hi there,

Thank you for sharing the information.

Could you please contact us for more details regarding why we deleted your debug output in our support center? You can reach us at support.rconfig.com.

Regarding the issue, I have attached an image showing how your Main Prompt command should appear. For more information, please refer to: https://docs.rconfig.com/devices/prompts/.

![image](https://github.com/user-attachments/assets/a9c345d1-28c9-4896-95e6-e270e9e010b3)

In your device configuration, please edit the prompt so that, instead of '#', you should have Switch-03#.

Thanks,
Daniel B
rConfig

**Comment by Wyatt-Black** [comment]
Hi Daniel,

The image attached below is how I have the Main Prompt currently configured. As far as I can see, I have the prompt configured as it should be; I am sure you can understand my confusion on this issue.

![rconfig prompt](https://github.com/user-attachments/assets/93e7c9b2-d00a-4c6c-91e2-7c5c6a30815e)

I will be reaching out on the support website shortly to confirm why the logs were deleted.

Thank you,
Wyatt Black

**Comment by Wyatt-Black** [comment]
Hello,

Any update on this issue? 

Thanks,
Wyatt Black

**Comment by rconfig** [comment]
Hi Wyatt, something odd about this. rConfig is supposed to retry only once, then kill the job, but in you case, it reties 5 times. Can you check in two places for more clues.
1. Settings> Application Logs. Anything in here related to this device and connection?
2. Two the logs on the disk. in /var/www/html/rconfig/storage/logs. Check for todays log file. Delete it and then run the download now. Anything in this like and exception that might cause an issue.

Feel free to post the logs here, but make sure they are sanitised of any sensitive data.

**Comment by Wyatt-Black** [comment]
Hello,

The activity logs are yielding no obvious results, the only outputs that appear are "Start device download for Switch-03 ID:2" and "CLI Download Started for rconfig:download-deviceIDs:2" and those repeat 5 times and then end.

I have run the debug command again and this time sanitized sensitive data (as far as I am aware). I will include that and the output of the laravel-2024-12-03.log file. As you can see in the logs I deleted the file, and then reran the job allowing it to only output the results from the single GUI job.

Debug output: 
[debug2.txt](https://github.com/user-attachments/files/17995621/debug2.txt)


Logs on disk:  
[laravel-2024-12-03.log](https://github.com/user-attachments/files/17995598/laravel-2024-12-03.log)

Thanks,
Wyatt Black

**Comment by stephenstack** [comment]
Thanks, quick thing to try, can you change the configured prompt to a lower case (switch-03#)

There are multiple 30 second timeouts in the output becuase of this. 
-> NET_SSH2_MSG_CHANNEL_DATA (since last: 30.0117, network: 0s)\r\n

It may or may or may not be causing the issue. But its worth cleaning it up. Please repost data once done

**Comment by Wyatt-Black** [comment]
Hi Stephen,

After changing the prompts to lowercase as requested, the jobs ran exactly as expected. I am unsure who played the cruel joke of naming half the switches all lowercase and the other half capitalized, but I finally have all configs backed up directly from the UI.

Thank you so much for your support in this!

Thank you again,
Wyatt Black

**Comment by stephenstack** [comment]
Thanks for your feedback. rConfig is a bit opinionated on the case for different reasons. New version next year will make this clear in the UI. Will close this for now 👍
