### ISSUE TITLE
LInks doesn't work

### ISSUE THREAD

**Issue by kova-ng** [rconfig/rconfig#148]
Installation links for rConfig v6 are dead for all distributions.

Can you reactivate links again?

**Comment by stephenstack** [comment]
is this still an issue?

**Comment by kova-ng** [comment]
Yes.

Ubuntu:
![image](https://github.com/user-attachments/assets/c375933e-580b-4919-a174-4d88e7cfb420)

Centos 9 / RockyLinux 9:
![image](https://github.com/user-attachments/assets/23be5d61-ffa7-47db-87e7-6ee8973e0530)

RHEL 8:

![image](https://github.com/user-attachments/assets/45b89903-52e5-4982-9aa2-103101110306)

**Comment by stephenstack** [comment]
thanks, those are old scripts. Please use the OS Setup scripts from these docs. 

https://docs.rconfig.com/getstarted/os-setup/

**Comment by kova-ng** [comment]
Ok, those links are for version 7.
Where can I find links for version 6?

**Comment by stephenstack** [comment]
same docs about will setup OS for V6 and V7
