### ISSUE TITLE
rconfig does not connect to the Aruba 2930F switch

### ISSUE THREAD

**Issue by GroD7667** [rconfig/rconfig#150]
**Describe the bug**
Good afternoon. After adding the device, rconfig cannot connect to Aruba 2930F. When adding the device, the standard settings were used. Tell me where to look and what to click so that it connects.

**To Reproduce**
1. Go to 'Templates'
2. Click on 'New template'
3. Click on 'New template'
4. Scroll down to 'Click to choose from imported'
5. Choose a vendor 'Aruba'
6. Choose a template 'Aruba2930F-SSH-NoEnable.yml'
7. Click on 'Save'
8. Set the file permissions for www-data 775
9. Go to 'Devices'
10. Click on 'New Device'
11. Entered all the required parameters
12. Click on 'Save'
13. See the status "Exclamation mark"
14. In Notifications error authentication or connection

**Expected behavior**
What needs to be done to make the connection take place.

**Screenshots**
![Снимок экрана 2024-12-19 152147](https://github.com/user-attachments/assets/5290a974-b07a-4e68-80e9-e0036be3a3b8)
![Снимок экрана 2024-12-19 152226](https://github.com/user-attachments/assets/60199362-fdd8-4452-bda9-be8ff24347aa)
![Снимок экрана 2024-12-19 152251](https://github.com/user-attachments/assets/fa805a01-a8b8-4c14-be74-7e1abd517779)
![Снимок экрана 2024-12-19 153351](https://github.com/user-attachments/assets/88317142-cc10-4295-9616-53bc7a87bb9d)

**rConfig Version Information (You can copy this from the rConfig dashboard):**
OS VERSION
Ubuntu 24.04.1 LTS
PHP / LARAVEL VERSION
8.3.14 / 11.25.0
REDIS VERSION
7.0.15
MYSQL VERSION
11.2.6 

**Logs info (can be retrieved from /var/www/html/rconfig6/storage/logs - try to paste relevant logs only)
[2024-12-19 11:25:07] production.ERROR: Symfony\Component\Mime\Address::__construct(): Argument #1 ($address) must be of type string, null given, called in /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Mail/Message.php on line 58 {"exception":"[object] (TypeError(code: 0): Symfony\\Component\\Mime\\Address::__construct(): Argument #1 ($address) must be of type string, null given, called in /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Mail/Message.php on line 58 at /var/www/html/rconfig/vendor/symfony/mime/Address.php:42)
 13710  [stacktrace]
 13711  #0 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Mail/Message.php(58): Symfony\\Component\\Mime\\Address->__construct()
 13712  #1 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(241): Illuminate\\Mail\\Message->from()
 13713  #2 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(214): Illuminate\\Notifications\\Channels\\MailChannel->addSender()
 13714  #3 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(176): Illuminate\\Notifications\\Channels\\MailChannel->addressMessage()
 13715  #4 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(84): Illuminate\\Notifications\\Channels\\MailChannel->buildMessage()
 13716  #5 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(316): Illuminate\\Notifications\\Channels\\MailChannel->Illuminate\\Notifications\\Channels\\{closure}()
 13717  #6 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(66): Illuminate\\Mail\\Mailer->send()
 13718  #7 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148): Illuminate\\Notifications\\Channels\\MailChannel->send()
 13719  #8 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106): Illuminate\\Notifications\\NotificationSender->sendToNotifiable()
 13720  #9 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
 13721  #10 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(101): Illuminate\\Notifications\\NotificationSender->withLocale()
 13722  #11 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(79): Illuminate\\Notifications\\NotificationSender->sendNow()
 13723  #12 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\\Notifications\\NotificationSender->send()
 13724  #13 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\\Notifications\\ChannelManager->send()
 13725  #14 /var/www/html/rconfig/vendor/spatie/laravel-health/src/Commands/RunHealthChecksCommand.php(116): Spatie\\Health\\Notifications\\Notifiable->notify()
 13726  #15 /var/www/html/rconfig/vendor/spatie/laravel-health/src/Commands/RunHealthChecksCommand.php(33): Spatie\\Health\\Commands\\RunHealthChecksCommand->sendNotification()
 13727  #16 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\\Health\\Commands\\RunHealthChecksCommand->handle()
 13728  #17 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
 13729  #18 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
 13730  #19 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
 13731  #20 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
 13732  #21 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
 13733  #22 /var/www/html/rconfig/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
 13734  #23 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
 13735  #24 /var/www/html/rconfig/vendor/symfony/console/Application.php(1047): Illuminate\\Console\\Command->run()
 13736  #25 /var/www/html/rconfig/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand()
 13737  #26 /var/www/html/rconfig/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
 13738  #27 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\\Component\\Console\\Application->run()
 13739  #28 /var/www/html/rconfig/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
 13740  #29 {main}
 13741  "}

**Additional context**
I've gone through a lot of options and I don't know where to look next.

**Comment by stephenstack** [comment]
is this still an issue?

**Comment by GroD7667** [comment]
Yes, but there is news. I checked the functionality on another switch, and everything worked there. Perhaps the problem is that on the first switch in the config there is a connection to the command switch.

**Comment by stephenstack** [comment]
Good to hear that. YEs, well worth checking the basics. Check out our doc below 
https://docs.rconfig.com/general/troubleshooting/

We'll close this, ping back if more help is needed
