### ISSUE TITLE
Problem with git clone

### ISSUE THREAD

**Issue by krajewmar** [rconfig/rconfig#151]
Not possible to clone rconfigv6 . OS Rocky9 linux

[root@localhost html]# git clone https://github.com/rconfig/rconfig.git
Klonowanie do „rconfig”...
fatal: brak dostępu do „https://github.com/rconfig/rconfig.git/”: The requested URL returned error: 403

**Comment by stephenstack** [comment]
Working fine, just tested this second. if your using a proxy server, that might be returning a 403 unauthorised error.

![image](https://github.com/user-attachments/assets/fc0a7244-3a4d-455a-b3df-5174250f5f0b)

**Comment by krajewmar** [comment]
It was an issue with silent drop on fortigate :( UTM didn't log the action.
But, finally, setup is completed :)
