### ISSUE TITLE
OS Setup for Rocky Linux is not working

### ISSUE THREAD

**Issue by Frowwny** [rconfig/rconfig#16]
Hi there,

I am using Rocky Linux 9 and i am trying to follow the OS Script install for Centos per the instructions and it wont install. See the output below.

[root@CMHome home]# wget https://www.rconfig.com/downloads/rconfig6_centos8.sh -O /home/install.sh
--2023-05-04 15:12:54--  https://www.rconfig.com/downloads/rconfig6_centos8.sh
Resolving www.rconfig.com (www.rconfig.com)... 74.234.33.54
Connecting to www.rconfig.com (www.rconfig.com)|74.234.33.54|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12000 (12K) [text/x-shellscript]
Saving to: ‘/home/install.sh’

/home/install.sh          100%[===================================>]  11.72K  --.-KB/s    in 0.1s    

2023-05-04 15:12:55 (109 KB/s) - ‘/home/install.sh’ saved [12000/12000]

[root@CMHome home]# chmod +x install.sh
[root@CMHome home]# sudo ./install.sh
Starting rConfig installation...
9
The OS version is not Centos 7 or 8.

**Comment by stephenstack** [comment]
We are currently developing a centos 9 installation script. Per Docs, right now centos/ rocky/ rhel 8 is supported
https://www.rconfig.com/docs/6.10/getstarted/os-setup

**Comment by Frowwny** [comment]
> We are currently developing a centos 9 installation script. Per Docs, right now centos/ rocky/ rhel 8 is supported https://www.rconfig.com/docs/6.10/getstarted/os-setup

Hi Stephen, I am using Rocky 9 at the moment and I went per the script and It will not work. So at the moment I cant install rConfig on Rocky Linux 9?

**Comment by TOAOQ** [comment]
Hej Frowwny, I had issues with installing on other Linux distro's as well... Then switched over to Rocky  8.7 (Green Obsidian) and with some minor issues all went well (see my earlier, now closed issue)>
You say you use Rocky 9, and the error ends with `The OS version is not Centos 7 or 8.`, any reason you are not trying the advised OS version?
Maybe try to install on version 8 and after a working install upgrade to version 9?

**Comment by rconfig** [comment]
Good morning all,

Centos/Rocky9 OS setup scripts have been released. See here. Please log any issues on a new issues ticket. 

https://www.rconfig.com/docs/6.10/getstarted/os-setup#centos
