### ISSUE TITLE
V4a - Install database error

### ISSUE THREAD

**Issue by SmokuSCB** [rconfig/rconfig#19]
Hi,
When i click in install database on installation process i recive error:
`Fail - DB ERROR: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE `profiles` ENABLE KEYS */' at line 5. We have deleted the DB that was created. Please check your settings and try again`
On the same server previously worked config v3.6.7

**Comment by spyderwylde** [comment]
Also running into this error

**Comment by josealf** [comment]
As shown in the commit, just remove extra comma at the end of line 501 in file www/install/rconfig.sql and try again.

**Comment by nizhnyk** [comment]
josealf, Comma should be replaced by semicolon. The actual create table statement is missing for profiles table in www/install/rconfig.sql

**Comment by rconfig** [comment]
fully updated sql file. please try again
