### ISSUE TITLE
Default Credentials

### ISSUE THREAD

**Issue by crayse1** [rconfig/rconfig#21]
When I enter my default credentials for all routers and switches I notice that it trims the password at the "&" character in my password. 

Thanks

**Comment by josealf** [comment]
I guess this is due to the fact that the ampersand is used to separate variables sent via GET and POST requests, so it should not be used in the passed values. If accepted, the value should be encoded, probably to base64 and possible decoded before stored to the database.

**Comment by josealf** [comment]
Yes, my guess is right. file www/js/configDevice.js in line 39 includes the following instruction:
`        url: 'lib/ajaxHandlers/ajaxConfigDevice.php?rid=' + rid + '&snipId=' + snippetId + '&username=' + deviceUsername + '&password=' + devicePassword,`
With the current code, there is no way to include some special characters in the password, most notably &.

**Comment by rconfig** [comment]
closing this as its not a problem item
