### ISSUE TITLE
uploading a connection profile

### ISSUE THREAD

**Issue by ciolben** [rconfig/rconfig#22]
Hello,
The message "Invalid File" appears when uploading a .php file for "Profile File" under Devices > Profiles.

Config: Client: IE 10, file from Win7, NTFS (obviously ;)), server under Centos 7
Possible Fix: under  _www/lib/crud/profiles.crud.php_, line 64:
`if ($_FILES["profileFile"]["type"] == "application/octet-stream" && $_FILES["profileFile"]["size"] < 20000) `
to
`if (($_FILES["profileFile"]["type"] == "application/octet-stream" || $_FILES["profileFile"]["type"] == "text/plain") && $_FILES["profileFile"]["size"] < 20000)`

Bye

**Comment by rconfig** [comment]
fixed, thank you

**Comment by rconfig** [comment]
fixed, thank you
