### ISSUE TITLE
Cannot delete entries from device event log

### ISSUE THREAD

**Issue by seanpdiaz** [rconfig/rconfig#22]
**Describe the bug**
I receive an error in the console when trying to delete events from the device event log. Once the delete button is clicked nothing happens and thus the logs are all still there.

**To Reproduce**
1. Go to a specific device in your inventory and then go to view all events and try to delete an event.
2. Open JS console and repeat step 1 and see error in console log.
3. Error presented is `o.deleteRow is not a function`

**Expected behavior**
I would expect that when you click the delete button of a row in the view all events of a device it will delete the row.

**Screenshots**
![Screenshot 2023-05-22 at 7 20 25 PM](https://github.com/rconfig/rconfig/assets/36584757/403d8421-f3ba-4d42-94fc-80d663a319f4)

**rConfig Version Information (You can copy this from the rConfig dashboard):**
OS VERSION
Ubuntu 22.04.2 LTS
SERVERNAME
rconfig-internal.diaz.lan
LOCAL IP
192.168.165.57
PUBLIC IP
PHP / LARAVEL VERSION
8.2.6 / 10.3.3
REDIS VERSION
6.0.16
MYSQL VERSION
10.6.12 

**Logs info (can be retrieved from /var/www/html/rconfig6/storage/logs - try to paste relevant logs only)
There was no applicable log information.

**Additional context**

**Comment by rconfig** [comment]
Confirmed, will work on update asap

**Comment by rconfig** [comment]
Please do a git pull and the follow command to recomplie the JS assets
npm run build

**Comment by seanpdiaz** [comment]
@rconfig thanks this now works
