### ISSUE TITLE
Error in SSH2

### ISSUE THREAD

**Issue by ciolben** [rconfig/rconfig#23]
Hello,

I get this error when using `dowloadNowScript.php`:

**Fatal error</b>:  Class 'phpseclib\Crypt\Random' not found /home/rconfig/classes/sshlib/Net/SSH2.php on line 1292**

With or without Composer. The best result would be to not depend on Composer.
I stopped investigating the error as I might misunderstand what is going on here, maybe somebody can help?

_Note: I see phpseclib is updated to the version 2, and need autoload.php which is not there._

**Comment by rconfig** [comment]
which version have you installed?

**Comment by ciolben** [comment]
Last from the repo (alpha 4).

**Comment by ZNiels** [comment]
i am currently having the same error in alpha4, have you found a solution for the error?

**Comment by ciolben** [comment]
No I don't... I haven't spent more time on this issue.

**Comment by rconfig** [comment]
closing this, a new V4 alpha will be released shortly
