### ISSUE TITLE
enable password needs to be blank

### ISSUE THREAD

**Issue by jacksonp2008** [rconfig/rconfig#25]
I have a number of FireEye devices that do not allow for an enable password, rather from the cli you just enter:

enable
show run

On the rConfig ui, it seems I cannot click the enable button and leave the password blank.  Is this something you can support?

thanks!

**Comment by jacksonp2008** [comment]
Anyone have thoughts on this?  I have the same issue with some non-cisco switches as well.  How to send enable with no password.

**Comment by josealf** [comment]
If there are no devices requiring an enable password, you may be able to achieve what you want as follows:
1. Set a dummy passowrd for the router.
2. commenting line sthat expect enable/send the enable password around lines 103-104 and 164-165 of file /classes/connection.class.php

**Comment by jacksonp2008** [comment]
Thanks Josealf, 

I have a mixture of both.  Those that have and require an enable password, and those that require the enable command but no password.  

So making it work for one will break it for the others.  Can you just accept a blank password?  tell me where this is in the code and I may be able to adjust myself.

thanks,
-Steve

**Comment by rconfig** [comment]
this is resolved in 3.8 beta. closing this
