### ISSUE TITLE
SSH and Telnet Authentication Errors

### ISSUE THREAD

**Issue by pbmorse** [rconfig/rconfig#26]
Hello,

Not sure if anyone else has had this issue. I am running rConfig 3.6.7 on CentOS7. Everything works great except that when I add a device to rConfig with SSH credentials and try to run a snippet in which is to copy my switch's running config to my TFTP server, the output of the command in rConfig says "Success: Connected to DUR-CSC-SWT-1-200 (192.168.1.200) for Router ID 1" but the running-config never gets backed up to my TFTP Server. When I go to the "Configuration Tools" section of rConfig and look at the connection log, the log shows this.
"CONN Error: Authentication Failed for 192.168.1.200 (File: /lib/ajaxHandlers/ajaxConfigDevice.php)
2016-09-26 12:23:56
CONN Success: Connected to DUR-CSC-SWT-1-200 (192.168.1.200) for Router ID 1 - in (File: /lib/ajaxHandlers/ajaxConfigDevice.php)

To double check I went into the command line of rConfig and was able to successfully connect to my switch via SSH and telnet connections that way. Double verified that all credentials are correct in rConfig Gui. Not sure why the log says that it connected but then immediately say that it failed. The switch that I am using is a Cisco SG300-10MP. I read in other post about changing the connection.class.php file to change the login username from "username:" to "User Name:" in which the SG300 series use but still no luck. I am new to rConfig and CentOS7, please excuse me for stupidity on this topic. Any help would be extremely appreciated.

**Comment by josealf** [comment]
You May want to try the latest git code. It includes fixes that could help with that issue.

**Comment by pbmorse** [comment]
Where would I get the latest git code for this. Thank you so much for your time? :)

Get Outlook for iOS




On Tue, Sep 27, 2016 at 12:58 PM -0500, "josealf" <notifications@github.com> wrote:










You May want to try the latest git code. It includes fixes that could help with that issue.

**Comment by josealf** [comment]
Download a zip snapshot of the master rconfig branch from https://github.com/rconfig/rconfig

**Comment by pbmorse** [comment]
Hey josealf, I downloaded the rconfig master branch in which downloaded as rconfig-master.zip.
My last question would be on how do I install this .zip into rConfig? Not sure what to do with it. Again thank you so much for your time and experience. I am a noob when it comes to learning CentOS and rConfig but actively researching on learning more about Centos etc.

**Comment by josealf** [comment]
pbmorse,

1. Make a zip or tar.gz of your current /home/rconfig directory. That way, you can't blame if something goes wrong :)

2. Expand the ZIP file in a suitable temporary area ( /tmp is fine). Run something like:
 unzip rconfig-master.zip
 
3. You only need to replace some files in your installation. Specifically:
config/functions.inc.php
lib/complianceScript.php
lib/configCategoryScript.php
lib/configDeviceScript.php
lib/downloadNowScript.php
lib/showCmdScript.php

While you are at it, also update:
www/js/devices.js
www/js/settings.js
www/settings.php 

You can use cp to update, like this:
cp /tmp/rconfig-master/lib/configCategoryScript.php  /home/rconfig/lib/configCategoryScript.php

Hope This helps,

**Comment by josealf** [comment]
See my answer in GitHub. I explain how to proceed on issue #26.

**Comment by pbmorse** [comment]
Hey josealf,

Yes I did try your method but still having the same problem. Theres some kind of bug in the Gui portion of rConfig. I can telnet and ssh into my switch all day long and run backups to my tftp server using the CLI portion of rConfig. Cant seem to pin point it.

**Comment by josealf** [comment]
Hi pbmorse, Sorry to read that. Do you still see the same errors in the logs ?

Regards

**Comment by pbmorse** [comment]
Hey josealf,

Okay so I decided to completely wipe everything and start over from scratch with a clean Cent OS7 and rConfig 3.6.7. Installed everything the right way and followed your directions copy the code from github into rconfig. rConfig can now pull switch configurations properly. Only thing that I am missing is how do I update/change the the command in which rConfig uses to pull the running config from a switch. Reason asking is that currently rConfig only pulls a small section of my switch's running configuration because the switch does not have the ability to turn off paging. When you do a show running config on a switch usually the output will show you a small portion of the running config then you have to hit the spacebar key to page down and view more of the confoguration one page at a time. I do know however that the Cisco SG300 series switches, if you invoke a "terminal datadump" then invoke the "show running-config" the switch will spit out the entire output in one fail swoop showing the whole config. I need to find a way in rConfig, when I hit the Manual Download button for rconfig to invoke the "terminal datadump" command on the switch before it decides to pull/backup the switches configuration, that way when it view it in rConfig, it shows the whole entire switch's config. Hope that makes sense. You have been so helpful and your a genius my friend!

Thank you so much!

**Comment by josealf** [comment]
pbmorse,

You're giving too much credit to me.  You should thank Stephen Stack, the author of rconfig. Go ahead and give him a star :)
Having said that, it looks like you can close this issue and open a new one for the paging issue with your switch. 
Most likely, you will need to modify file classes/connection.class.php. 
You may fix your issue by replacing lines 169 and 180 with:
            `$ssh->write("terminal datadump\n");`
instead of
            `$ssh->write("terminal length 0\n");`
The bad news is that this will create problems with other device types. So, instead of replacing that lines, you may get better results by adding (inserting) these lines after the CURRENT lines 170 and 181:
            `$ssh->write("terminal datadump\n");`
 `$ssh->read('/' . $prompt . '/', NET_SSH2_READ_REGEX);`

Try it and let us know how it goes. I know it is an ugly hack, but someday you won't need to do it.

**Comment by josealf** [comment]
Hi pbmorse,
I wonder if my last suggestions regarding the terminal datadump issue worked? I wrote those on the github thread for this issue.

regards,Jose

**Comment by pbmorse** [comment]
Hi josealf,

Yes it worked perfectly! Thank you so much for your help, you were a blessing my friend. :)
