### ISSUE TITLE
Write to Memory

### ISSUE THREAD

**Issue by pbmorse** [rconfig/rconfig#27]
I am wanting to run a scheduled task every night using a snippet which would
invoke the "Copy running-config startup-config" command or "Write Mem" to any switches that I would like.
Only problem is when I issue the command the switch ask if I would like to proceed in overwriting the startup-config file and presents the (yes/no)? prompt.

How do I create a snippet in rconfig to tell the switch to say Yes and continue with the command?

I tried the command in the snippet box as:
Write mem
Y

This doe not seem to work. The switches that I use are Cisco Sg300 series switches.

Thanks!

**Comment by josealf** [comment]
Use `terminal no prompt`
 command to disable the terminal prompts. 
See http://www.cisco.com/c/dam/en/us/td/docs/switches/lan/csbms/sf30x_sg30x/administration_guide/CLI_300_1_2_9.pdf

**Comment by rconfig** [comment]
closing due to no repsonse
