### ISSUE TITLE
Connection Port resets to 23

### ISSUE THREAD

**Issue by rsaeks** [rconfig/rconfig#29]
If a required field is left blank, the connection port resets to 23, even if SSHv2 is select. Prior to clicking "Save" with a missing required field, the Connection Port is at 22 as expected. However, if a required field is not included, the port resets to 23, while retaining all the other selected fields. Connection port field should retain it's value as all other fields on the page already do.

**Comment by rconfig** [comment]
moving this to WIP

**Comment by rconfig** [comment]
resolved in 3.7.2
