### ISSUE TITLE
Cant create/edit templates 

### ISSUE THREAD

**Issue by keoliscaen** [rconfig/rconfig#32]
**Describe the bug**

Hello, in my case I can't edit and create templates. I create him I got the notifications " Template added" but nothing appears. 

**To Reproduce**
1. Go to 'Templates'
2. Click on 'New Template'
3. Create ur 'template'

**Expected behavior**

The creation of my template appear

**Screenshots**
![image](https://github.com/rconfig/rconfig/assets/113020129/8f67e5b8-be5e-40ba-868b-ee733aeff37a)

This is the template I want to create : 

![image](https://github.com/rconfig/rconfig/assets/113020129/d4ada030-69c1-47c9-8fca-fae8d7a2ebfa)

**rConfig Version Information (You can copy this from the rConfig dashboard):**
OS VERSION
Ubuntu 20.04
PHP / LARAVEL VERSION
8.2 / 10.3.3
REDIS VERSION
?
MYSQL VERSION
10.3.35 

**Logs info (can be retrieved from /var/www/html/rconfig6/storage/logs - try to paste relevant logs only)

**Additional context**

I can't make " chown -R apache /home/rconfig" cause I dont got user Apache 

Cordially,

**Comment by stephenstack** [comment]
Hi 

What is the error you get? I dont see it above

**Comment by keoliscaen** [comment]
Hello, I  solved this problem on my own I was missing the rights modification part, nevertheless I don't understand the new way of working (I used to use version 3), the automatic download via automated tasks doesn't work because the device ID is missing when I create the task: 
![image](https://github.com/rconfig/rconfig/assets/113020129/ab1d9f24-591e-4770-a655-2f611073ef70)

When I run the CLI command with the device ID, it works:
![image](https://github.com/rconfig/rconfig/assets/113020129/60ed5d50-1d31-4810-95e5-43c1f5a14156)

I have the impression that rconfig doesn't make the link between the name of my equipment and its ID and therefore it doesn't include the device ID value in its command.

I must be misunderstanding the new way of working, can you clarify this for me? 

Cordially,

**Comment by keoliscaen** [comment]
Hello, I update the ticket, when I launch my scheduled task via the web interface or the command interface I realize that the task launches but that it does not really start and that it remains at 0% for a long time (more than 15 minutes), the scheduled task contains only one switch so it is not a volume problem. Nor do I get any error when I inspect the page on the web interface. I don't know where to look. 

Looking forward to your help.

Best regards,

**Comment by rconfig** [comment]
Hi

This is likely and issue with rconfig connecting to the device. Please review the queue manager, and troubleshoot with the docs and videos below. 
https://docs.rconfig.com/settings/queues
https://docs.rconfig.com/general/troubleshooting
https://www.youtube.com/@rconfigtutorialsvideos5999

The issues log is reserved for bugs and issues only. Because the reported issue is resolved, I will close this.
