### ISSUE TITLE
Schedule Tasks not working

### ISSUE THREAD

**Issue by rconfiguser** [rconfig/rconfig#34]
Hi ,i have installed the free version of rconfig core and i take the attached error when i try to run a schedule job.
Could you please provide our help ?

![2023_06_07_20_07_48_rConfig6_Network_Configuration_Management](https://github.com/rconfig/rconfig/assets/135863157/e283d64f-4d18-4a63-9e6b-3356ecc8e8a7
![2023-06-07 20_02_20-NCM__rconfig](https://github.com/rconfig/rconfig/assets/135863157/f6c728fa-de67-459f-8380-10fef3ef9904)
![2023_06_07_20_07_48_rConfig6_Network_Configuration_Management](https://github.com/rconfig/rconfig/assets/135863157/bf889d72-86e8-429e-b5d8-5d9f5a4bb33d)

**Comment by rconfiguser** [comment]
To clarify show the attached screenshot
![2023-06-08 19_33_52-Window](https://github.com/rconfig/rconfig/assets/135863157/8fe55c98-e728-4264-9cbd-f2f5f3832453)

**Comment by stephenstack** [comment]
Seems like the app does not have permissions to create the folder required. 

Try to set the disk permissions correctly. 

chown -R apache /var/www/html/rconfig/storage

**Comment by rconfiguser** [comment]
Hi Stephen, i have already done it  and doesn't work.
I add in FileOperations.php in the 79 line mkdir($this->catfolder,0777, true); and it works smoothly.
