### ISSUE TITLE
HP switch support for telnet and ssh in beta version 4

### ISSUE THREAD

**Issue by roinro** [rconfig/rconfig#34]
Hi guys,

Thank you for your efforts in creating this configuration management system.
I installed the beta version and I find the new "profile" feature a smart move.
Yet, i was not able to successfully connect to an HP switch, either through telnet or ssh.
I was playing with the profiles, buy adding new ones and modifying it to send carriage return [ENTER] when the HP screen come up. The telnet, HP profile and default profile for SSH doesn't work for my switch ProCurve J4904A Switch 2848 software revision I.10.107. 
I would really appreciate some help.
Thank you grand.

**Comment by rconfig** [comment]
this will work in v4. in development at the moment

**Comment by fams** [comment]
Where can  I find v4 github?

**Comment by rconfig** [comment]
please email stpehen@rconfig.com and I will add you to the beta

**Comment by roinro** [comment]
Hi Stephen,
Please advise what is the status of the v4? I would be glad to test the new features in works.
I'm not sure if you have the intent to add ftp/tftp capability as it is not very hard to integrate this capability to pool and deploy configuration with simple scripting.
Thank you again for your continuous support.
Regards,
Adrian 

    On Tuesday, July 4, 2017 3:21 AM, Stephen Stack <notifications@github.com> wrote:
 

 this will work in v4. in development at the moment—

**Comment by rconfig** [comment]
this is being worked on in the private 3.8 beta. closing this
