### ISSUE TITLE
enhancement idea: remove all logs from device

### ISSUE THREAD

**Issue by lolmachine4** [rconfig/rconfig#36]
Hi,

it would be nice to be able to purge all Device Event Log-entries at once, similiar to device-configs, which can all be purged at once.
Would be especially usefull when testing, I generated alot of errors and info entries, but there is no checkbox to mark them all and delete atleast a whole page.

**Comment by rconfig** [comment]
Thanks for the suggestion, I will add this to our internal feature tracker. If you are able, you are welcome to build out the feature yourself and PR the feature.
