### ISSUE TITLE
Not Installable per Guide... php artisan install   exec npm run dev stuck forever

### ISSUE THREAD

**Issue by ludwigma** [rconfig/rconfig#4]
**Describe the bug**
New Rocky Linux 8.7 Minimal Install as the Guide says ..nothing else
Used the scripts for all packages

**To Reproduce**
The Guide

**Screenshots**
![image](https://user-images.githubusercontent.com/32019055/226636117-bad7e3ab-00b5-46c5-b66d-951127336847.png)
i reproduced it twice with new VM´s
started php artisan install with -v for detailed view where its stuck

i can start npm run dev without the script without a problem

**rConfig Version Information (You can copy this from the rConfig dashboard):**
I cant even start rconfig to see the dashboard

This Versions got installed via your script
OS VERSION
Rocky 8.7 (Green Obsidian)
PHP / LARAVEL VERSION
8.1.17 / 10.3.3
REDIS VERSION
5.0.3
MYSQL VERSION
10.3.35  mariadb

**Logs info (can be retrieved from /var/www/html/rconfig6/storage/logs - try to paste relevant logs only)
no logs available

**Additional context**

**Comment by stephenstack** [comment]
Hi,

Two things to try. First rerun the commmand with the -v switch at the end. This should give more output and let us know where it is getting stuck. 
2. If you get a 'connect ENETUNREACH on npm' command, export the following env var
`export NODE_OPTIONS="--dns-result-order=ipv4first"`
You can run this on the command line and also add this to the ~./bashrc file

**Comment by ludwigma** [comment]
this is the -v output ! and i dont get the ENETUNREACH error  
if you look at the screenshot you see that is is exported anyway

i dont even use the dev stuff , i just want to run it

**Comment by SpoCo-network1** [comment]
FWIW, I am getting this exact same issue going through the installation guide. "php artisan install" hangs at "npm run dev" for an infinite amount of time. Let it run for over an hour...

**Comment by stephenstack** [comment]
Ok, lets keep a calm respectful tone. 

Try running the command from the rConfig folder. 
npm run dev

also, try an 

npm run build

Send the output for review

**Comment by ludwigma** [comment]
as i said in the first post i can start npm run dev without a problem without the script :


  VITE v3.2.5  ready in 512 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose

  LARAVEL v10.3.3  plugin v0.6.1

  ➜  APP_URL:     --> this is private  fqdn is correct  

--------------------------------------------

npm run build also runs without the script:

npm run build

> rconfig6@1.0.0 build
> vite build

vite v3.2.5 building for production...
✓ 1298 modules transformed.
public/build/assets/rconfig_msp_576.ff43b60e.png                            271.72 KiB
public/build/assets/rconfig_msp_768.6dc1843d.png                            469.55 KiB
public/build/assets/RedHatDisplay-Regular.e6fb83d9.woff2                    28.07 KiB
public/build/assets/RedHatDisplay-Medium.6d3ccc0f.woff2                     27.99 KiB
public/build/assets/RedHatText-Medium.eb14b046.woff2                        28.37 KiB
public/build/assets/RedHatDisplay-updated-Regular.d0b90ff3.woff2            25.13 KiB
public/build/assets/RedHatDisplay-updated-Medium.da0621a9.woff2             25.91 KiB
public/build/assets/RedHatDisplay-updated-Bold.66d1fc26.woff2               25.75 KiB
public/build/assets/RedHatText-updated-Regular.2e08dbe8.woff2               25.16 KiB
public/build/assets/RedHatText-updated-Medium.721ddd64.woff2                26.01 KiB
public/build/assets/RedHatMono-updated-Regular.1686cd5c.woff2               20.44 KiB
public/build/assets/RedHatDisplayVFModified-updated.3a6592a3.woff2          30.06 KiB
public/build/assets/RedHatDisplayVF-updated-ItalicModified.8483eece.woff2   31.26 KiB
public/build/assets/RedHatTextVFModified-updated.942d38f7.woff2             29.39 KiB
public/build/assets/RedHatTextVF-updated-ItalicModified.9e1c1004.woff2      31.20 KiB
public/build/assets/RedHatMonoVF-updated.4cca9c27.woff2                     28.46 KiB
public/build/assets/RedHatMonoVF-updated-Italic.ca135ebd.woff2              31.73 KiB
public/build/assets/overpass-thin.e85966f1.woff2                            32.91 KiB
public/build/assets/overpass-thin-italic.44db8e3d.woff2                     35.06 KiB
public/build/assets/overpass-extralight.f053be7c.woff2                      34.23 KiB
public/build/assets/overpass-extralight-italic.d23afde2.woff2               35.94 KiB
public/build/assets/overpass-light.9db6ab0a.woff2                           33.66 KiB
public/build/assets/overpass-light-italic.ec333948.woff2                    35.72 KiB
public/build/assets/overpass-regular.8e2261df.woff2                         34.30 KiB
public/build/assets/overpass-italic.34df3d81.woff2                          36.49 KiB
public/build/assets/overpass-semibold.3d06895e.woff2                        32.63 KiB
public/build/assets/overpass-semibold-italic.ae706d8c.woff2                 36.04 KiB
public/build/assets/overpass-bold.5c4ed5bb.woff2                            33.94 KiB
public/build/assets/overpass-bold-italic.16cda7ef.woff2                     36.38 KiB
public/build/assets/overpass-extrabold.648ba0e7.woff2                       33.02 KiB
public/build/assets/overpass-mono-light.5bae063c.woff2                      48.94 KiB
public/build/assets/overpass-mono-regular.a13dec50.woff2                    50.32 KiB
public/build/assets/overpass-mono-semibold.b39c5174.woff2                   50.11 KiB
public/build/assets/overpass-mono-bold.2bf715ff.woff2                       50.36 KiB
public/build/assets/fa-solid-900.f419ad7a.woff2                             77.25 KiB
public/build/assets/pficon.86c74539.woff2                                   17.29 KiB
public/build/assets/pfbg_576.1d76d6cc.jpg                                   65.91 KiB
public/build/assets/pfbg_576@2x.4942ea78.jpg                                191.01 KiB
public/build/assets/pfbg_768.8bc3cc8a.jpg                                   113.96 KiB
public/build/assets/pfbg_768@2x.037bce76.jpg                                353.55 KiB
public/build/assets/pfbg_2000.1f17de55.jpg                                  269.96 KiB
public/build/assets/status-icon-sprite.bc89cb14.svg                         3.44 KiB
public/build/assets/overpass-heavy.5e0869ee.woff2                           34.80 KiB
public/build/assets/overpass-extrabold-italic.a258578a.woff2                35.80 KiB
public/build/assets/overpass-heavy-italic.8f5fbf20.woff2                    37.08 KiB
public/build/assets/RedHatDisplay-Bold.ca18645c.woff2                       28.36 KiB
public/build/assets/RedHatText-Regular.542423d0.woff2                       27.51 KiB
public/build/assets/rconfig_msp_992.dc932bbc.png                            658.05 KiB
public/build/assets/pfbg_992@2x.9dfd9687.jpg                                574.78 KiB
public/build/assets/rconfig_msp_576@2x.70e161ad.png                         922.22 KiB
public/build/assets/rconfig_msp_768@2x.c73fc521.png                         1589.28 KiB
public/build/assets/RedHatDisplay-Regular.1b99a560.woff                     35.58 KiB
public/build/assets/RedHatDisplay-Medium.6ccf2158.woff                      35.68 KiB
public/build/assets/RedHatText-Medium.702e86ff.woff                         36.23 KiB
public/build/assets/overpass-thin.6feca5dc.woff                             39.90 KiB
public/build/assets/overpass-thin-italic.2dffa092.woff                      42.48 KiB
public/build/assets/overpass-extralight.64fbbd3d.woff                       41.54 KiB
public/build/assets/overpass-extralight-italic.6cbe5597.woff                43.62 KiB
public/build/assets/overpass-light.3f8151f4.woff                            40.95 KiB
public/build/assets/overpass-light-italic.a1454ca5.woff                     43.33 KiB
public/build/assets/overpass-regular.16b63547.woff                          41.59 KiB
public/build/assets/overpass-italic.b81a6146.woff                           44.18 KiB
public/build/assets/overpass-semibold.ec5809e8.woff                         39.67 KiB
public/build/assets/overpass-semibold-italic.1935eb14.woff                  43.68 KiB
public/build/assets/overpass-bold.452a631f.woff                             41.12 KiB
public/build/assets/overpass-bold-italic.4926428e.woff                      44.01 KiB
public/build/assets/overpass-extrabold.613313c8.woff                        40.40 KiB
public/build/assets/overpass-mono-light.7fbe3706.woff                       61.84 KiB
public/build/assets/overpass-mono-regular.95881615.woff                     63.51 KiB
public/build/assets/overpass-mono-semibold.085fb4a8.woff                    63.42 KiB
public/build/assets/overpass-mono-bold.9b29c79a.woff                        63.54 KiB
public/build/assets/fa-solid-900.e14bf851.woff                              99.83 KiB
public/build/assets/pficon.0a333dac.woff                                    20.57 KiB
public/build/assets/overpass-heavy.c7e67c68.woff                            42.30 KiB
public/build/assets/overpass-extrabold-italic.33533562.woff                 43.35 KiB
public/build/assets/overpass-heavy-italic.c702fef1.woff                     44.65 KiB
public/build/assets/RedHatDisplay-Bold.44214a55.woff                        36.05 KiB
public/build/assets/RedHatText-Regular.df36d7d0.woff                        35.14 KiB
public/build/assets/rconfig_msp_2000.c67fbc6d.png                           2277.15 KiB
public/build/assets/rconfig_msp_992@2x.0d27509e.png                         2493.94 KiB
public/build/assets/codicon.bff90e92.ttf                                    71.15 KiB
public/build/manifest.json                                                  66.94 KiB
public/build/assets/Dashboard.02931ec7.js                                   15.33 KiB / gzip: 3.86 KiB
public/build/assets/CopyLogo.2f51e1c8.js                                    0.93 KiB / gzip: 0.56 KiB
public/build/assets/Devices.b0b10932.js                                     27.04 KiB / gzip: 7.40 KiB
public/build/assets/DeleteModal.18b28643.js                                 1.46 KiB / gzip: 0.74 KiB
public/build/assets/DevicesBreadcrumbs.16fc5596.js                          3.79 KiB / gzip: 0.81 KiB
public/build/assets/DevicesForm.6ee2c54b.js                                 24.48 KiB / gzip: 5.99 KiB
public/build/assets/SideDrawer.2615a3c7.js                                  1.79 KiB / gzip: 0.87 KiB
public/build/assets/ViewFunctions.e6931cf5.js                               2.94 KiB / gzip: 0.96 KiB
public/build/assets/createResizableColumn.f52f352c.js                       5.51 KiB / gzip: 1.85 KiB
public/build/assets/DataTableSpinner.27bf9ae6.js                            0.69 KiB / gzip: 0.35 KiB
public/build/assets/DeviceCategoryField.aa31413a.js                         3.97 KiB / gzip: 1.52 KiB
public/build/assets/MultiSelect.a449fdba.js                                 4.59 KiB / gzip: 1.82 KiB
public/build/assets/LoadingSpinner.3f17d573.js                              0.54 KiB / gzip: 0.34 KiB
public/build/assets/DeviceConfigs.95d7a737.js                               14.04 KiB / gzip: 4.62 KiB
public/build/assets/DataTableToolbar.fdd86633.js                            2.40 KiB / gzip: 0.99 KiB
public/build/assets/DeviceViewConfig.8942a04b.js                            14.22 KiB / gzip: 4.23 KiB
public/build/assets/HelpContent.fb6c5507.js                                 3.55 KiB / gzip: 1.14 KiB
public/build/assets/DeviceEventLog.33949360.js                              2.29 KiB / gzip: 1.11 KiB
public/build/assets/DataTable.e25e9d48.js                                   7.79 KiB / gzip: 2.73 KiB
public/build/assets/DeviceViewDeviceDetailsDescr.26dbb11e.js                0.95 KiB / gzip: 0.58 KiB
public/build/assets/Templates.296948f0.js                                   17.61 KiB / gzip: 5.79 KiB
public/build/assets/PageHeader.30ca36c9.js                                  0.67 KiB / gzip: 0.41 KiB
public/build/assets/Tags.bd0e8781.js                                        6.08 KiB / gzip: 2.22 KiB
public/build/assets/ConfigSearch.6ef650dc.js                                12.10 KiB / gzip: 3.83 KiB
public/build/assets/ConfigReports.291bf1f4.js                               10.67 KiB / gzip: 3.73 KiB
public/build/assets/Settings.cf38decc.js                                    3.00 KiB / gzip: 1.29 KiB
public/build/assets/0Overview.2b47bd6f.js                                   0.71 KiB / gzip: 0.41 KiB
public/build/assets/1System.a38aaa96.js                                     20.47 KiB / gzip: 4.93 KiB
public/build/assets/4Security.8cebc13c.js                                   0.93 KiB / gzip: 0.47 KiB
public/build/assets/10About.adc1e7d2.js                                     3.69 KiB / gzip: 1.21 KiB
public/build/assets/Users.4e382518.js                                       9.23 KiB / gzip: 3.36 KiB
public/build/assets/Categorys.a4aa5a91.js                                   6.08 KiB / gzip: 2.16 KiB
public/build/assets/ActivityLog.afbbf572.js                                 11.86 KiB / gzip: 3.92 KiB
public/build/assets/scrollToBottom.9505217d.js                              0.14 KiB / gzip: 0.13 KiB
public/build/assets/abap.59d36112.js                                        14.07 KiB / gzip: 5.35 KiB
public/build/assets/apex.0e775ffd.js                                        4.10 KiB / gzip: 1.86 KiB
public/build/assets/azcli.829845db.js                                       1.07 KiB / gzip: 0.45 KiB
public/build/assets/bat.633facbe.js                                         2.04 KiB / gzip: 0.98 KiB
public/build/assets/bicep.1d8ae12f.js                                       2.72 KiB / gzip: 1.08 KiB
public/build/assets/cameligo.86abe115.js                                    2.37 KiB / gzip: 1.07 KiB
public/build/assets/PageNotFound.d1f8838d.js                                1.42 KiB / gzip: 0.74 KiB
public/build/assets/coffee.121835a7.js                                      3.75 KiB / gzip: 1.42 KiB
public/build/assets/cpp.842d3355.js                                         5.59 KiB / gzip: 2.21 KiB
public/build/assets/UsersForm.7c35c2cb.js                                   7.81 KiB / gzip: 2.07 KiB
public/build/assets/Vendors.6ad624c2.js                                     5.06 KiB / gzip: 2.03 KiB
public/build/assets/clojure.d05e66c6.js                                     9.66 KiB / gzip: 3.65 KiB
public/build/assets/cypher.fb1dee97.js                                      3.55 KiB / gzip: 1.53 KiB
public/build/assets/dart.272dab62.js                                        4.39 KiB / gzip: 1.74 KiB
public/build/assets/dockerfile.339e94af.js                                  2.07 KiB / gzip: 0.79 KiB
public/build/assets/ecl.5e606247.js                                         5.46 KiB / gzip: 2.33 KiB
public/build/assets/elixir.a31f9bb7.js                                      10.23 KiB / gzip: 2.58 KiB
public/build/assets/flow9.9a099d7d.js                                       2.01 KiB / gzip: 0.96 KiB
public/build/assets/fsharp.c69c757d.js                                      3.15 KiB / gzip: 1.42 KiB
public/build/assets/freemarker2.1d801f84.js                                 16.05 KiB / gzip: 4.21 KiB
public/build/assets/csp.6487bf60.js                                         1.63 KiB / gzip: 0.65 KiB
public/build/assets/go.51190b50.js                                          2.83 KiB / gzip: 1.25 KiB
public/build/assets/handlebars.7f91e325.js                                  6.95 KiB / gzip: 1.75 KiB
public/build/assets/hcl.6b7d1742.js                                         3.75 KiB / gzip: 1.59 KiB
public/build/assets/html.3cae6440.js                                        5.23 KiB / gzip: 1.54 KiB
public/build/assets/ini.d9bdfd1c.js                                         1.32 KiB / gzip: 0.66 KiB
public/build/assets/java.676f2079.js                                        3.39 KiB / gzip: 1.50 KiB
public/build/assets/javascript.622d64ce.js                                  1.21 KiB / gzip: 0.63 KiB
public/build/assets/typescript.95a3c4d2.js                                  5.61 KiB / gzip: 2.28 KiB
public/build/assets/julia.cd8e9036.js                                       7.29 KiB / gzip: 2.69 KiB
public/build/assets/csharp.99014f3e.js                                      4.66 KiB / gzip: 1.82 KiB
public/build/assets/kotlin.3c1f4364.js                                      3.60 KiB / gzip: 1.57 KiB
public/build/assets/lexon.8cccca16.js                                       2.62 KiB / gzip: 1.04 KiB
public/build/assets/lua.862aa9c4.js                                         2.31 KiB / gzip: 1.04 KiB
public/build/assets/liquid.876d322b.js                                      4.20 KiB / gzip: 1.79 KiB
public/build/assets/m3.b04cedb5.js                                          2.99 KiB / gzip: 1.41 KiB
public/build/assets/markdown.387e712e.js                                    3.94 KiB / gzip: 1.48 KiB
public/build/assets/mips.7baeae7c.js                                        2.76 KiB / gzip: 1.19 KiB
public/build/assets/msdax.7d31f0e2.js                                       5.04 KiB / gzip: 2.05 KiB
public/build/assets/mysql.294467b0.js                                       11.25 KiB / gzip: 4.10 KiB
public/build/assets/graphql.543bb499.js                                     2.45 KiB / gzip: 1.14 KiB
public/build/assets/pascal.904b60df.js                                      3.17 KiB / gzip: 1.50 KiB
public/build/assets/pascaligo.41c33333.js                                   2.19 KiB / gzip: 1.03 KiB
public/build/assets/perl.8a45027d.js                                        8.30 KiB / gzip: 3.16 KiB
public/build/assets/pgsql.a50388b6.js                                       13.39 KiB / gzip: 4.52 KiB
public/build/assets/php.38bacf90.js                                         8.08 KiB / gzip: 2.15 KiB
public/build/assets/pla.218e59ed.js                                         1.88 KiB / gzip: 0.77 KiB
public/build/assets/objective-c.f18e8e14.js                                 2.59 KiB / gzip: 1.17 KiB
public/build/assets/powerquery.5cd0c42d.js                                  16.78 KiB / gzip: 4.89 KiB
public/build/assets/powershell.a8cf2d39.js                                  3.43 KiB / gzip: 1.47 KiB
public/build/assets/protobuf.c4730c63.js                                    9.07 KiB / gzip: 2.15 KiB
public/build/assets/pug.888c3b71.js                                         4.96 KiB / gzip: 1.74 KiB
public/build/assets/python.cdfe7bd1.js                                      3.86 KiB / gzip: 1.73 KiB
public/build/assets/qsharp.6181ba65.js                                      3.11 KiB / gzip: 1.46 KiB
public/build/assets/css.2d6e4cde.js                                         4.64 KiB / gzip: 1.49 KiB
public/build/assets/r.0e27b978.js                                           3.30 KiB / gzip: 1.39 KiB
public/build/assets/less.d79b8bf9.js                                        4.05 KiB / gzip: 1.52 KiB
public/build/assets/redshift.0fa6ffde.js                                    11.76 KiB / gzip: 4.35 KiB
public/build/assets/restructuredtext.9f8faf2b.js                            4.04 KiB / gzip: 1.47 KiB
public/build/assets/ruby.2d2470af.js                                        8.54 KiB / gzip: 2.64 KiB
public/build/assets/rust.73ed1828.js                                        4.30 KiB / gzip: 1.91 KiB
public/build/assets/sb.8b234b1c.js                                          2.03 KiB / gzip: 0.95 KiB
public/build/assets/scala.9d75cee2.js                                       7.39 KiB / gzip: 2.17 KiB
public/build/assets/scheme.364f9acb.js                                      1.97 KiB / gzip: 0.93 KiB
public/build/assets/scss.3d57ef5d.js                                        6.50 KiB / gzip: 1.85 KiB
public/build/assets/shell.b5c40754.js                                       3.24 KiB / gzip: 1.32 KiB
public/build/assets/solidity.c28bcbdf.js                                    18.40 KiB / gzip: 4.47 KiB
public/build/assets/sophia.752f8778.js                                      2.94 KiB / gzip: 1.31 KiB
public/build/assets/sparql.ce6c4000.js                                      2.73 KiB / gzip: 1.27 KiB
public/build/assets/sql.45ce0396.js                                         10.30 KiB / gzip: 3.89 KiB
public/build/assets/st.3de0725b.js                                          7.46 KiB / gzip: 2.31 KiB
public/build/assets/swift.d68f2794.js                                       5.29 KiB / gzip: 2.15 KiB
public/build/assets/systemverilog.d9ceb9af.js                               7.67 KiB / gzip: 2.82 KiB
public/build/assets/tcl.ac67f306.js                                         3.73 KiB / gzip: 1.47 KiB
public/build/assets/twig.afe51c44.js                                        6.07 KiB / gzip: 1.62 KiB
public/build/assets/vb.f69dd588.js                                          5.90 KiB / gzip: 2.15 KiB
public/build/assets/xml.752df9f6.js                                         2.69 KiB / gzip: 1.12 KiB
public/build/assets/yaml.cb6537ac.js                                        4.24 KiB / gzip: 1.64 KiB
public/build/assets/cssMode.be31d57c.js                                     32.98 KiB / gzip: 8.74 KiB
public/build/assets/htmlMode.1cbc724c.js                                    33.52 KiB / gzip: 8.86 KiB
public/build/assets/jsonMode.5b7cdf06.js                                    38.88 KiB / gzip: 10.84 KiB
public/build/assets/tsMode.57991929.js                                      22.24 KiB / gzip: 6.43 KiB
public/build/assets/Devices.1bb0ba86.css                                    0.24 KiB / gzip: 0.15 KiB
public/build/assets/CopyLogo.51bc45f0.css                                   0.12 KiB / gzip: 0.09 KiB
public/build/assets/DeviceViewConfig.ff7f105f.css                           1.69 KiB / gzip: 0.26 KiB
public/build/assets/DeviceConfigs.a87ea005.css                              0.13 KiB / gzip: 0.08 KiB
public/build/assets/Settings.c2af4a03.css                                   0.07 KiB / gzip: 0.09 KiB
public/build/assets/postiats.9c6d18fe.js                                    7.91 KiB / gzip: 2.50 KiB
public/build/assets/DeviceView.70c9b39a.js                                  23.56 KiB / gzip: 6.15 KiB
public/build/assets/Commands.b102b93b.js                                    11.93 KiB / gzip: 4.03 KiB
public/build/assets/razor.aac5d49b.js                                       8.91 KiB / gzip: 2.42 KiB
public/build/assets/Tasks.a851d74b.js                                       90.27 KiB / gzip: 20.47 KiB
public/build/assets/redis.4877fd8d.js                                       3.71 KiB / gzip: 1.59 KiB
public/build/assets/ConfigFullScreenView.abf960f0.css                       101.71 KiB / gzip: 16.49 KiB
public/build/assets/app.0a37be7f.css                                        1560.81 KiB / gzip: 150.09 KiB
public/build/assets/app.3e3e9863.css                                        1560.94 KiB / gzip: 150.15 KiB
public/build/assets/app.f0b08bf4.js                                         1213.14 KiB / gzip: 369.90 KiB
public/build/assets/ConfigFullScreenView.484dc0f3.js                        2848.35 KiB / gzip: 721.91 KiB

**Comment by SpoCo-network1** [comment]
@stephenstack stephenstack thank you for being so responsive! My tone is one of gratefulness. Very excited to use this software after following it's progress for over a year.

**Comment by stephenstack** [comment]
Please let me know the output of the following also.

node -v
npm -v

**Comment by ludwigma** [comment]
node -v
v19.8.1
npm -v
9.5.1

**Comment by rconfig** [comment]
ok, a fix was deployed. Either start the process from scratch, and re-clone the repo. Or run a 'git pull' from inside the rconfig folder. Then run the install again

**Comment by SpoCo-network1** [comment]
That got me through to the end of the script! Progress!
I noticed in the install instructions, the next section involves updating a apache file located (rhel) in /etc/httpd/conf.d/rconfig-vhost.conf

That file doesn't exist for me. Do you have an example file to provide or should one of the scripts dropped that file?

Thanks!!

**Comment by ludwigma** [comment]
the symlinks are created in the root directory of the server / 
rconfig-vhost.conf -> /var/www/html/rconfig/rconfig-vhost.conf
i think that shouldnt be there

also this symlink horizon_supervisor.ini -> /var/www/html/rconfig/horizon_supervisor.ini
 is in the root /



if you copy it to httpd/conf.d it starts now ...but only in http

**Comment by SpoCo-network1** [comment]
That's interesting. I didn't have any symlinks. rconfig-vhost.conf was not present in apache directory and there was no symlink to it. I ended up just copying it to /etc/httpd/conf.d/ and then apache started without issue.

In this case one could either update the documentation to include a step to copy that vhost file to the correct apache directory (depending on linux flavor) or script in a symlink or direct copy in one of the installation scripts.

**Comment by ludwigma** [comment]
i dont have the supervisor ini in the httpd directory ... dont know if i need that there

i think it should be in this dir, then restart the supervisord 
 /etc/supervisord.d/

**Comment by rconfig** [comment]
If you could rerun the process would be appreciate the script for the supervisor and apache installation and just not reliable when running via PHP scripts. Added steps in the readme, and some bash scripts to simplify.

**Comment by SpoCo-network1** [comment]
Thank you @rconfig for being responsive and resolving these issues. Since I have a working installation in dev/test I won't re-run the process right now, but can do this later for prod.

**Comment by ludwigma** [comment]
Thanks for your help !!

**Comment by SpoCo-network1** [comment]
@rconfig Are you retaining the Compliance and Config Tools feature sets of rconfig for your paid support model? Your readme states: "fully functional version of rConfig v6, with all the core features of rConfig v6 Professional, but with some limitations."
Could you please provide more clarity around "some limitations" so that users looking to evaluate this v6 product know what features they will be able to use? This is in no way meant to be challenging, but to simply ask for clarity surrounding what features are and are not available to "core" users. I must admit that I would really like to see the features I described available. Configuration comparison, compliance, and reporting are things we need in a product like this. I really like what I see so far.
