### ISSUE TITLE
OS Setup script fails for NTP (CentOS 9 and clones)

### ISSUE THREAD

**Issue by kiptonui** [rconfig/rconfig#41]
The install.sh script as part of the OS Setup phase is attempting to install ntp when using the script version for RHEL 9 based systems
NTP is not part of RHEL 9 so this fails and should be using chrony instead.  This results in a "broken" time service as NTP fails to install and chrony is also not installed.

**To Reproduce**
Use the steps for CentOS/Rocky9
```
cd /home
yum -y install wget
wget https://www.rconfig.com/downloads/rconfig6_centos9.sh -O /home/install.sh
chmod +x install.sh
./install.sh
```

The install.sh will print
`Error: Unable to find a match: ntp vixie-cron`

**Expected behavior**
The installer script should install chrony and start the service

**Screenshots**
n/a

**rConfig Version Information (You can copy this from the rConfig dashboard):**
OS VERSION
Alma Linux 9.2 (Turquoise Kodkod)

**Comment by stephenstack** [comment]
Thanks for the feedback. Our setup scripts have been updated. Could you try that out again and let us know if its resolved?

**Comment by stephenstack** [comment]
Closing, marked resolved
