### ISSUE TITLE
Some issues observed on Ubuntu . Problem with templates

### ISSUE THREAD

**Issue by ravelundwork** [rconfig/rconfig#42]
rConfig 6 Open Source installed on Ubuntu 22.04.2 LTS

Some issues
1. Horizon does not start automatically. (starting it manual by running php artisan horizon &

2. Cannot create new template from the web ui. Template say it is successfully created but is never shown in the list.

3. Cannot import Templates.  Getting error message:

{ "data": { "message": "Server Error" }, "status": 500, "statusText": "Internal Server Error", "headers": { "cache-control": "no-cache, private", "connection": "close", "content-type": "application/json", "date": "Wed, 05 Jul 2023 12:38:40 GMT", "server": "Apache/2.4.52 (Ubuntu)" }, "config": { "transitional": { "silentJSONParsing": true, "forcedJSONParsing": true, "clarifyTimeoutError": false }, "adapter": [ "xhr", "http" ], "transformRequest": [ null ], "transformResponse": [ null ], "timeout": 0, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1, "maxBodyLength": -1, "env": {}, "headers": { "Accept": "application/json, text/plain, */*", "X-Requested-With": "XMLHttpRequest", "X-XSRF-TOKEN": "eyJpdiI6ImM0T1dHRHo1SC9FNlFBaEVsNVpxcmc9PSIsInZhbHVlIjoiM0cxVDd6bUVzdlF2TXhHUDBmTjJZZDluTEZRRzdFTHh4ekJkQ0lMYi9NYXBIRzlqM0VFZllZTDhzT1dDeVVNREtCVExWK2xmYk1xUllKMXBpellJUlRTaDdXaVI4UXNYUU1ncFZKY0w4b2pkNHJZUEk5TUNTQm5oWmpZbmdSRjIiLCJtYWMiOiI1YzdmYjllM2I5YmQ2ZGUwN2ViYzU4MzhkNzYyMThiNWI2MTlhNDMxMDc5NTRkY2Y0NjFiZGMyYTc1ZmU1NjNiIiwidGFnIjoiIn0=" }, "method": "get", "url": "/api/import-github-templates" }, "request": "[object XMLHttpRequest]" }

**Comment by stephenstack** [comment]
open the .env file in the application folder (`/var/www/html/rconfig/,env`)
Change 
```BASH
APP_DEBUG=true
```
Save and exit
from `/var/www/html/rconfig/`
run 
```BASH
php artisan rconfig:clear-all
```
Try the steps again. You will get better information from the debug output for the 500 error.

**Comment by ravelundwork** [comment]
Seems like a permission issue

The stream or file "/var/www/html/rconfig/storage/logs/laravel-2023-07-06.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/rconfig/storage/logs/laravel-2023-07-06.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/rconfig/storage/logs/laravel-2023-07-06.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/rconfig/storage/logs/laravel-2023-07-06.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/rconfig/storage/logs/laravel-2023-07-06.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/rconfig/storage/logs/laravel-2023-07-06.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/rconfig/storage/logs/laravel-2023-07-06.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/rconfig/storage/logs/laravel-2023-07-06.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/rconfig/storage/logs/laravel-2023-07-06.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/rconfig/storage/logs/laravel-2023-07-06.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/rconfig/storage/logs/laravel-2023-07-06.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: file_put_contents(/var/www/html/rconfig/storage/app/rconfig/templates/test.yml): Failed to open stream: Permission denied Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}} Context: {"userId":1,"exception":{}}

**Comment by stephenstack** [comment]
For permissions issues, please see the docs for the relevant command to help. 
https://docs.rconfig.com/general/cli-commands#rconfigclear-all

```bash
cd /var/www/html/rconfig
php artisan rconfig:clear-all
```

If this does not work, on Ubuntu systems you can try this
```bash
cd /var/www/html/rconfig
chown -R www-data storage
```

**Comment by ravelundwork** [comment]
Using the chown command did the trick. The rconfg:clear-all did not seem to do antthing.
But the chown fixed the issue. Thanks
