### ISSUE TITLE
show running-config next page

### ISSUE THREAD

**Issue by Tomisago** [rconfig/rconfig#43]
Good afternoon

I would be glad if you help me.

I installed rconfig6 core and check if it works. I have a HP Aruba device and I need the output of the "show running-config" command to work completely, at the moment when working out "show running-config" I do not save the full output because "HP Aruba" requires you to click next page: space. How to send space keystrokes? How to make "screen length" or "no page"?

**Comment by stephenstack** [comment]
We have connection templates for Aruba devices in the templates repo. 
[https://github.com/rconfig/rConfig-templates/tree/master/Aruba ](https://github.com/rconfig/rConfig-templates/tree/master/Aruba )

You can set the paging disable command in the connection template.

![image](https://github.com/rconfig/rconfig/assets/7944609/263519de-6392-48a8-b3a4-e4ba765ffa16)

**Comment by Tomisago** [comment]
Thanks for the answer.

Is there a limit to saving the output of commands?
