### ISSUE TITLE
3.8Beta - templateId and deviceEnablePrompt columns are missing from nodes table

### ISSUE THREAD

**Issue by jdcraymond** [rconfig/rconfig#44]
Cannot add a node in 3.8beta as the templateId amd deviceEnablePrompt columsn are not created in the nodes table.

Not listed in the rconfig.sql file.

**Comment by jdcraymond** [comment]
Looks like just adding those columns doesn't fix it.  Other items seem to be missing.  Need an updated rconfig.sql

**Comment by rconfig** [comment]
checking this

**Comment by rconfig** [comment]
can you run the install  again with the latest 3.8 downloaded from the website. post the results in slack

**Comment by rconfig** [comment]
X
