### ISSUE TITLE
[Q] changing IP address of the server 

### ISSUE THREAD

**Issue by lolmachine4** [rconfig/rconfig#44]
Hey,
please point me in the right direction.
I've changed the IP of the rocky-server via nmtui  - cli-utility. The server is reachable via the new IP and everything seems to work, but the dashboard is still showing the old IP address. 
How can I fix this?

kind regards

**Comment by rconfig** [comment]
That specific content is cached using redis. You can login to redis on the cli and clear the cache directly. You can use the clear-all command per the docs to clear out the cache, or you can wait :)
