### ISSUE TITLE
3.8 beta - Templating needs separate enable username for HPE ArubaOS devices

### ISSUE THREAD

**Issue by mcramer85** [rconfig/rconfig#45]
So far the templating won't work for HPE/ArubaOS devices which will need the enable command. When logging in with an unprivileged user after sending the "enable" command ArubaOS will ask for an additional Username...

Screenshot:
![arubaos_enable_prompt](https://user-images.githubusercontent.com/31223045/29536729-3a931c5a-86bf-11e7-91e7-9ed5fbc91b3b.png)

**Comment by rconfig** [comment]
updating tags/ looking at this today

**Comment by rconfig** [comment]
@mcramer85 can you post a debug output 
Please change the showCmdScript.php file to use the newly created connection3.class.php file. 

Then Post following;
1. device make/ model/ code rev you are trying to connect to
2. post the connection template file here
Go to settings page, enable 'Device debugging Output' and run the showCmdScript.php, with the 'true' keyword/ parameter after the taskID i.e. showCmdScript.php 123456 true

**Comment by mcramer85** [comment]
[20170828-02_debug_connection.txt](https://github.com/rconfig/rconfig/files/1256607/20170828-02_debug_connection.txt)

Debugging output attached - but I got stack at the point that ArubaOS displays a disclaimer after the first successful login which needs to get confirmed.

At the moment I can't find any way to disable the disclaimer.

**Comment by rconfig** [comment]
resolved with templates. needs template created and tested
