### ISSUE TITLE
Cant download Mikrotik config

### ISSUE THREAD

**Issue by Edrard** [rconfig/rconfig#46]
Good day

Trying to use Mikrotik template and its not work. Tryed on version 7.10.1 and 6 48.6

**To Reproduce**
Add Mikrotik template from there - https://github.com/rconfig/rConfig-templates/blob/master/Mikrotik/mikrotek-ssh-noenable.yml
Add category Mikrotik
Create Command export and select category Mikrotik
Add vendor Mikrotik
Add tag Mikrotik
Add device Mikrotik with tag, category and vendor Mikrotik
Press button download now

**Expected behavior**
Config must be downloaded

**Screenshots**
![image](https://github.com/rconfig/rconfig/assets/1434437/c459ae54-8357-4c70-a9d7-1bf12da30547)

OS VERSION
Rocky Linux release 8.8
PHP 8.1.21 / Laravel Framework 10.12.0
REDIS VERSION
5.0.3
MYSQL VERSION
10.5.21

<html>
<body>

ErrorException: preg_match(): Compilation failed: range out of order in character class at offset 21 in /var/www/vhosts/rconfig.vamark.com/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3018
--
Stack trace:
#0 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /var/www/vhosts/rconfig.vamark.com/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3018): preg_match()
#3 /var/www/vhosts/rconfig.vamark.com/app/Http/Controllers/Connections/SSH/SendCommand.php(45): phpseclib3\Net\SSH2->read()
#4 /var/www/vhosts/rconfig.vamark.com/app/Http/Controllers/Connections/SSH/SendCommand.php(32): App\Http\Controllers\Connections\SSH\SendCommand->ansiShowCommand()
#5 /var/www/vhosts/rconfig.vamark.com/app/Http/Controllers/Connections/SSHConnectionManager.php(80): App\Http\Controllers\Connections\SSH\SendCommand->sendShowCommand()
#6 /var/www/vhosts/rconfig.vamark.com/app/Http/Controllers/Connections/SSHConnectionManager.php(41): App\Http\Controllers\Connections\SSHConnectionManager->sendSSHCommand()
#7 /var/www/vhosts/rconfig.vamark.com/app/Http/Controllers/Connections/MainConnectionManager.php(36): App\Http\Controllers\Connections\SSHConnectionManager->SSHConnectionAndOutput()
#8 /var/www/vhosts/rconfig.vamark.com/app/CustomClasses/DeviceDownloadClass.php(52): App\Http\Controllers\Connections\MainConnectionManager->setupConnectAndReturnOutput()
#9 /var/www/vhosts/rconfig.vamark.com/app/Console/Commands/rconfigDeviceDownload.php(46): App\CustomClasses\DeviceDownloadClass->downloadDevices()
#10 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\rconfigDeviceDownload->handle()
#11 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#13 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#14 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#15 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\Container\Container->call()
#16 /var/www/vhosts/rconfig.vamark.com/vendor/symfony/console/Command/Command.php(312): Illuminate\Console\Command->execute()
#17 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Symfony\Component\Console\Command\Command->run()
#18 /var/www/vhosts/rconfig.vamark.com/vendor/symfony/console/Application.php(1040): Illuminate\Console\Command->run()
#19 /var/www/vhosts/rconfig.vamark.com/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
#20 /var/www/vhosts/rconfig.vamark.com/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
#21 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(163): Symfony\Component\Console\Application->run()
#22 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(381): Illuminate\Console\Application->call()
#23 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Illuminate\Foundation\Console\Kernel->call()
#24 /var/www/vhosts/rconfig.vamark.com/app/Jobs/DownloadConfigNow.php(41): Illuminate\Support\Facades\Facade::__callStatic()
#25 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\DownloadConfigNow->handle()
#26 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#27 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#28 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#29 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#30 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#31 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#32 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#34 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow()
#35 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#36 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126): Illuminate\Pipeline\Pipeline->then()
#38 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#39 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#40 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\Queue\Jobs\Job->fire()
#41 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\Queue\Worker->process()
#42 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\Queue\Worker->runJob()
#43 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\Queue\Worker->daemon()
#44 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\Queue\Console\WorkCommand->runWorker()
#45 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\Queue\Console\WorkCommand->handle()
#46 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#47 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#48 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#49 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#50 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#51 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\Container\Container->call()
#52 /var/www/vhosts/rconfig.vamark.com/vendor/symfony/console/Command/Command.php(312): Illuminate\Console\Command->execute()
#53 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Symfony\Component\Console\Command\Command->run()
#54 /var/www/vhosts/rconfig.vamark.com/vendor/symfony/console/Application.php(1040): Illuminate\Console\Command->run()
#55 /var/www/vhosts/rconfig.vamark.com/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
#56 /var/www/vhosts/rconfig.vamark.com/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
#57 /var/www/vhosts/rconfig.vamark.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(200): Symfony\Component\Console\Application->run()
#58 /var/www/vhosts/rconfig.vamark.com/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#59 {main}

</body>
</html>

**Comment by stephenstack** [comment]
Hi

Have you applied the mikrotik connection template to this device. And you will also deen to append the username with +cte
https://github.com/rconfig/rConfig-templates/tree/master/Mikrotik

**Comment by stephenstack** [comment]
Closing as no update
