### ISSUE TITLE
3.8 Beta - $devicePassword and $deviceEnablePassword are not set if the passwords aren't encrypted

### ISSUE THREAD

**Issue by jdcraymond** [rconfig/rconfig#48]
If passwords are not encrypted, $devicePassword and  $deviceEnablePassword variables do not get set in showCmdScript.php

Running via CLI get the following errors:

PHP Notice:  Undefined variable: devicePassword in /home/rconfig/lib/showCmdScript.php on line 141
Notice: Undefined variable: devicePassword in /home/rconfig/lib/showCmdScript.php on line 141
PHP Notice:  Undefined variable: deviceEnablePassword in /home/rconfig/lib/showCmdScript.php on line 142
Notice: Undefined variable: deviceEnablePassword in /home/rconfig/lib/showCmdScript.php on line 142

I changed the following for troubleshooting

      if(KEY != '') {
            $devicePassword = encrypt_decrypt('decrypt', $device['devicePassword']);
            $deviceEnablePassword = encrypt_decrypt('decrypt', $device['deviceEnablePassword']);
        } 
to
        if(KEY != '') {
            $devicePassword = encrypt_decrypt('decrypt', $device['devicePassword']);
            $deviceEnablePassword = encrypt_decrypt('decrypt', $device['deviceEnablePassword']);
        } else {
            $devicePassword = $device['devicePassword'];
            $deviceEnablePassword = $device['deviceEnablePassword'];
        }
:

**Comment by rconfig** [comment]
resolved with your proposed fixes. thanks
