### ISSUE TITLE
reset.blade.php bad image reference

### ISSUE THREAD

**Issue by 6r1zzlyB** [rconfig/rconfig#48]
The resources/views/auth/passwords/reset.blade.php is calling a missing image file.

`<img class="login-pf-brand" src="/images/rConfig_white_horizontal_128px.png" alt=" logo" />`

and resources/views/auth/passwords/email.blade.php looks to have a similar reference.

There are no "rConfig_white_horizontal_128px.png" in "public/images"

**Comment by rconfig** [comment]
Resolved with PR #52
Thanks for the feedback. Update per the docs
https://github.com/rconfig/rconfig#update
