### ISSUE TITLE
Horizon Not Running

### ISSUE THREAD

**Issue by BennyDaBee** [rconfig/rconfig#50]
**Describe the bug**
Horizon is not running so no tasks or downloads ever run

**To Reproduce**
1. Dashboard Shows Horizon Not Running
2. Ran the install at root

**Expected behavior**
Horizon to be running to be able to do tasks

**Screenshots**

**rConfig Version Information (You can copy this from the rConfig dashboard):**
OS VERSION
Ubuntu 22.04.2 LTS
PHP / LARAVEL VERSION
8.2.8/10.12.0
REDIS VERSION
6.0.16
MYSQL VERSION
10.6.12 

**Logs info (can be retrieved from /var/www/html/rconfig6/storage/logs - try to paste relevant logs only)
No log related to Horizon

**Comment by BennyDaBee** [comment]
Did run the update commands to see if something may have been missed but no luck. url/horizon/dashboard shows a 500 Error

**Comment by BennyDaBee** [comment]
Did end up fixing this. I used Ubuntu 20.04 instead, but I did have to edit /etc/supervisor/supervisord.conf and in the includes add 

files = /etc/supervisor/*.ini

However, url/horizon/dashboard still shows 500 error, but tasks queue and run now.

**Comment by stephenstack** [comment]
Check the horizon logs. Should be located at /var/www/html/rconfig/storage/logs/horizon.log
Check the latest Laravel log file in that location also, for exception errors.

**Comment by BennyDaBee** [comment]
Horizon Log shows no errors. Laravel log only shows that I dont have my email configured properly.

**Comment by 6r1zzlyB** [comment]
I had a similar issue. I believe I solved it by running the command below.

```
cd /var/www/html/rconfig
chown -R www-data storage
```

**Comment by rconfig** [comment]
thanks @6r1zzlyB 

@BennyDaBee did this resolve the issue for you?

**Comment by BennyDaBee** [comment]
I have been travelling, but I ended up going back to rConfig 3 for the meantime.

**Comment by BennyDaBee** [comment]
As well though, this is for a improvement, when I put it behind a reverse proxy with SSL, Nginx Proxy Manager, it would only serve assets in HTTP so the browser would not serve the page properly.

**Comment by stephenstack** [comment]
I would love to get you on v6 core. V3 is way deprecated. Anyway, i will close for now, reach if anything else is needed.
