### ISSUE TITLE
beta - downloadConfiguration is not working due deviceEnable field does not exist in table

### ISSUE THREAD

**Issue by fams** [rconfig/rconfig#54]
I'm receiving this error on phpLog during downloadConfig.
[13-Sep-2017 11:08:40 America/Sao_Paulo] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deviceEnableMode' in 'field list' in /hom
e/rconfig/classes/db2.class.php:65
Stack trace:
#0 /home/rconfig/classes/db2.class.php(65): PDOStatement->execute()
#1 /home/rconfig/classes/db2.class.php(69): db2->execute()
#2 /home/rconfig/lib/downloadNowScript.php(57): db2->resultset()
#3 /home/rconfig/www/lib/ajaxHandlers/ajaxDownloadNow.php(16): include('/home/rconfig/l...')
#4 {main}
  thrown in /home/rconfig/classes/db2.class.php on line 65

**Comment by rconfig** [comment]
Per #40 manual download not working yet. This is next to be refactored. Closing this
