### ISSUE TITLE
Httpd conf

### ISSUE THREAD

**Issue by Greeniezz** [rconfig/rconfig#54]
Hi,

Sorry to bother, i just installed everything, every steps went smooth but my httpd server is still on the TEST page :'(

Any help please :D

Thank you very much in advance

**Comment by Greeniezz** [comment]
I complete the rconfig-vhost.conf file but still nothing, i'm on CentOS 9

**Comment by stephenstack** [comment]
Httpd -S

Run this on the CLI. Might give us a clue

**Comment by Greeniezz** [comment]
here is the result :
VirtualHost configuration:
*:80                   NAME.DOMAIN.LOCAL (/etc/httpd/conf.d/rconfig-vho                                                                           st.conf:1)
*:443                  NAME.DOMAIN.LOCAL (/etc/httpd/conf.d/ssl.conf:40                                                                           )
ServerRoot: "/etc/httpd"
Main DocumentRoot: "/var/www/html"
Main ErrorLog: "/etc/httpd/logs/error_log"
Mutex proxy: using_defaults
Mutex authn-socache: using_defaults
Mutex ssl-cache: using_defaults
Mutex default: dir="/etc/httpd/run/" mechanism=default
Mutex cache-socache: using_defaults
Mutex authdigest-opaque: using_defaults
Mutex watchdog-callback: using_defaults
Mutex proxy-balancer-shm: using_defaults
Mutex rewrite-map: using_defaults
Mutex ssl-stapling-refresh: using_defaults
Mutex authdigest-client: using_defaults
Mutex lua-ivm-shm: using_defaults
Mutex ssl-stapling: using_defaults
PidFile: "/etc/httpd/run/httpd.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="apache" id=48
Group: name="apache" id=48


I changed the name of the server to be anonymous, thank you for your help !

**Comment by Greeniezz** [comment]
I can't access the web server using http, i only got the http test page when using https

**Comment by stephenstack** [comment]
I'm sure the space in this is not intentional, or might be a bac copy/ paste. But check it anyway. 

*:80 NAME.DOMAIN.LOCAL (/etc/httpd/conf.d/rconfig-v**ho s**t.conf:1)

If there is a space in the file name, fix it and restart httpd

**Comment by Greeniezz** [comment]
I just redo the whole installation and now i can access via http to the rconfig server ! Thank your for your help, i really appreciate it
Is there a way to activate https instead ?

**Comment by stephenstack** [comment]
Glad to hear it. 
SSL implementation very much depends on your preferences and requirements. Types and locations of Certs and keys etc.. 
But we have a doc to guide you how to use Letsencrypt. https://docs.rconfig.com/other/ssl-setup
