### ISSUE TITLE
3.8Beta - Cannot enable Encryption through Settings page

### ISSUE THREAD

**Issue by jdcraymond** [rconfig/rconfig#56]
On the settings page, trying to enable encryption, after going through all the prompts, backing up, setting key, etc encryption is still disabled.

Needed to change Line 21 of ajaxEncryptPasswords.php from

if(!$db2->resultsetCols()[0] == 1){

to

if($db2->resultsetCols()[0] == 1){

(removing the ! for the not)

**Comment by rconfig** [comment]
can you test again, works on my dev system without changes

**Comment by jdcraymond** [comment]
In testing again, I get the same thing issue as above.

**Comment by rconfig** [comment]
resolved... thanks
