### ISSUE TITLE
f_install_base_pkgs() function failing to install packages

### ISSUE THREAD

**Issue by kiptonui** [rconfig/rconfig#56]
**Description**
When running install.sh to deploy OS content on AlmaLinux 9.2 the function f_install_base_pkgs fails to install (or attempt to install) all packages.

`yum -y install chrony sudo telnet bind-utils traceroute tree zip unzip vixie-cron crontabs telnet`
also
`yum -y install openssl-devel openssl mod_ssl supervisord`

is incorrect as supervisord does not exist, but this is mitigated by the "supervisor" package install as part of "f_install_redis_supervisor()" later on

Due to the large size of the Development Tools groupinstall and the ambiguous nature of them being "base" packages, I feel like this would be better served as its own function in order to distinguish its state and large output.  The remainder of the critical base packages can then be better highlighted if there is an issue.

**To Reproduce**
1. Create new system with Alma 9
2. Follow steps on the OS Setup guide https://docs.rconfig.com/getstarted/os-setup, specifically
```
cd /home
yum -y install wget
wget https://www.rconfig.com/downloads/rconfig6_centos9.sh -O /home/install.sh
chmod +x install.sh
./install.sh
```
4. Test for package presence
`for i in chrony sudo telnet bind-utils traceroute tree zip unzip vixie-cron crontabs telnet; do printf "%20s : $(rpm -q $i)\n" $i; done`
will result in 
```
              chrony : package chrony is not installed
                sudo : sudo-1.9.5p2-9.el9.x86_64
              telnet : package telnet is not installed
          bind-utils : package bind-utils is not installed
          traceroute : package traceroute is not installed
                tree : tree-1.8.0-10.el9.x86_64
                 zip : zip-3.0-35.el9.x86_64
               unzip : unzip-6.0-56.el9.x86_64
          vixie-cron : package vixie-cron is not installed
            crontabs : crontabs-1.11-27.20190603git.el9_0.noarch
              telnet : package telnet is not installed
```

vixie-cron also does not exist anymore and cronie should be the package used instead ... 
The others all exist and can be installed individually.  

This also does not work by running the command at cli so it seems like a more specific upstream bug.  I haven't found anything describing the behaviour elsewhere, but to mitigate it, it is probably better to install all packages in "f_install_base_pkgs" via loop and then test for dnf/yum response

**Expected behavior**
All dependent packages are installed and errors are either trapped or warned.

**Screenshots**
n/a

**rConfig Version Information (You can copy this from the rConfig dashboard):**
OS VERSION
AlmaLinux release 9.2 (Turquoise Kodkod)
PHP / LARAVEL VERSION
N/A
REDIS VERSION
N/A
MYSQL VERSION
N/A

**Installation output***
Note the lack of reference to packages I have marked as missing above.

Starting base package installation... Hold on a few minutes!
...
all this installs correctly
...
Last metadata expiration check: 2:40:37 ago on Tue Aug 22 14:03:17 2023.
Package sudo-1.9.5p2-9.el9.x86_64 is already installed.
Package tree-1.8.0-10.el9.x86_64 is already installed.
Package zip-3.0-35.el9.x86_64 is already installed.
Package unzip-6.0-56.el9.x86_64 is already installed.
_No match for argument: vixie-cron_
Package crontabs-1.11-27.20190603git.el9_0.noarch is already installed.
_Error: Unable to find a match: vixie-cron_
Last metadata expiration check: 2:40:38 ago on Tue Aug 22 14:03:17 2023.
Package openssl-devel-1:3.0.7-17.el9_2.x86_64 is already installed.
Package openssl-1:3.0.7-17.el9_2.x86_64 is already installed.
Package mod_ssl-1:2.4.53-11.el9_2.5.x86_64 is already installed.
_No match for argument: supervisord_
_Error: Unable to find a match: supervisord_
Last metadata expiration check: 2:40:38 ago on Tue Aug 22 14:03:17 2023.
Package git-2.39.3-1.el9_2.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

Base package installation update completed!

**Comment by stephenstack** [comment]
AlmaLinux has its own repo and packages, which are not accounted for in the OS setup scripts. List of supports OSs are on the page you reference above. Alma is not on that list. 
https://docs.rconfig.com/getstarted/os-setup/

As you have downloaded the OS setup script, i would be happy for you to update that script and submit it back as a contribution. I can have the team update the docs and upload for consumption.

**Comment by kiptonui** [comment]
The packages (except for vixie-cron and supervisord) exist in the AlmaLinux repos.  I can hand install them.

At the moment it is a (more or less) 1:1 compatible source with Rocky/RHEL 9.2, obviously this is going to change soon with Alma opting for ABI compatibility, but currently with 9.2 there should be no divergence.

vixie-cron doesn't even exist on CentOS 7.9, it should still exist elsewhere that sysv is still used, but not on Fedora based systems.

I'm assuming supervisord presence in the function is either a typo of supervisor or a hangover from previous installer versions particularly as its called out as its own install function later.

I will look at updating the script.

**Comment by kiptonui** [comment]
@stephenstack I've made some updates for the script that I'd like to try and contribute back (including some additional fixes  and enhancements for other parts of the installer).  

Having forked the repo, I can't find where in the repo the rconfig6_centos_9.sh is created/generated. If you could point me in the right direction I will create a PR for it.  Alternatively I can paste my update here.

**Comment by stephenstack** [comment]
Can you send a note via https://www.rconfig.com/#contact and you can share the script direct. The script is hosted on our website and while open, is not available for collaboration. Appreciate your support

**Comment by stephenstack** [comment]
Script received, will review and make available asap. Closing this for now. Thanks much for the contribution
