### ISSUE TITLE
3.8beta - Encryption if statement is backwards in ajaxGetDefaultUserPass.php

### ISSUE THREAD

**Issue by jdcraymond** [rconfig/rconfig#58]
If Encryption is disabled, checking Default username/password when adding/editing a device, it will try to decrypt a non encrypted default password.

If Encryption is enabled, checking Default username/password when adding/editing a device, it will encrypt an encrypted default password again.

Line 22 of ajaxGetDefaultUserPass.php needs to be changed from

if($db2->resultsetCols()[0] == 0){

to 

if($db2->resultsetCols()[0] == 1){

**Comment by rconfig** [comment]
resolved
