### ISSUE TITLE
3.8Beta - HP Procurve VT100 Escape characters being captured

### ISSUE THREAD

**Issue by jdcraymond** [rconfig/rconfig#59]
When grabbing the output of the HP Procurve, it captures VT100 escape characters such as

[24;1H[2K[24;1H[1;24r[24;1H

Ie,

spanning-tree
spanning-tree Trk1 priority 4
spanning-tree Trk2 priority 4
[24;1H[2K[24;1H[1;24r[24;1Hspanning-tree Trk3 path-cost 10000
spanning-tree Trk3 priority 4

**Comment by jdcraymond** [comment]
Not sure the best way to handle this, ie strip them out in the code or you can also run

config term
console local-terminal none
exit

before the other commands

**Comment by rconfig** [comment]
can you edit your template to test the 'console local-terminal none' command. You will have to do it on one single line, so add line breaks. Your template section should look like this;

config:
    # Disable config scrolling/ paging command. on/off
    paging: on
    # Disable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    pagingCmd: " config term\n console local-terminal none\n exit"
    # re-enable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    resetPagingCmd: ""

**Comment by rconfig** [comment]
Hi, will need to build a new template for this post 3.8 release. For now, this is on hold
