### ISSUE TITLE
3.8 beta Error geting configuration from Mikrotik

### ISSUE THREAD

**Issue by alexvoinea1** [rconfig/rconfig#60]
I've imported the Mikrotik template and are able to authenticate on the switch but I get the following  message when it tries to run the export command:

PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/rconfig/classes/sshlib/Net/SSH2.php on line 2396

Notice: ob_flush(): failed to flush buffer. No buffer to flush in /home/rconfig/classes/sshlib/Net/SSH2.php on line 2396
<pre>
<- NET_SSH2_MSG_CHANNEL_DATA (0.0309s)
00000000                                                   ^......./..[9999
00000010                                                   B..[9999B....[99
00000020                                                   99B[rconfig@Mikr
00000030                                                   oTik] >

</pre>
PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/rconfig/classes/sshlib/Net/SSH2.php on line 2396

Notice: ob_flush(): failed to flush buffer. No buffer to flush in /home/rconfig/classes/sshlib/Net/SSH2.php on line 2396
<pre>
-> NET_SSH2_MSG_CHANNEL_DATA (0.0001s)
00000000                                                   ^........export.

</pre>
PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/rconfig/classes/sshlib/Net/SSH2.php on line 2396

Notice: ob_flush(): failed to flush buffer. No buffer to flush in /home/rconfig/classes/sshlib/Net/SSH2.php on line 2396
<pre>
<- NET_SSH2_MSG_CHANNEL_DATA (0.004s)
00000000                                                   ^........export

**Comment by rconfig** [comment]
this will be address as a template issue after 3.8 release.
