### ISSUE TITLE
After running 38upgscript.sh, config.inc.php is blank

### ISSUE THREAD

**Issue by jdcraymond** [rconfig/rconfig#63]
Ran the upgrade, said it completed successfully, but config.inc.php is size 0 bytes and blank.

38upgscript.sh outputted the following during Step 6

sed: -e expression #1, char 167: unknown option to `s'

This was on CentOS 6

**Comment by rconfig** [comment]
will test this on centos 6 as soon as I can. thanks

**Comment by rconfig** [comment]
unable to confirm, no further reports. Closing forr now
