### ISSUE TITLE
Fatal error memory size downloading Cisco Configuration

### ISSUE THREAD

**Issue by alexvoinea1** [rconfig/rconfig#65]
On a Cisco SG300-52 when trying to download the configuration the following error occurs:
Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 8192 bytes) in /home/rconfig/classes/sshlib/Crypt/DES.php on line 1260
Segmentation fault (core dumped)

On other Cisco models the download works

**Comment by rconfig** [comment]
Please follow the instructions here and post the output. Remove any passwords

https://www.rconfig.com/rconfig-support/knowledge-base/39-troubleshooting-showcmdscript-php-console-output

**Comment by alexvoinea1** [comment]
[root@rconfig-ct www]# php /home/rconfig/lib/showCmdScript.php 254070 true
The /home/rconfig/lib/showCmdScript.php script was run from a manual invocation on a shell with Task ID:254070
8 October 2017 03:57:32 AM
Array
(
    [id] => 3
    [deviceName] => SG
    [deviceIpAddr] => xxx.xxx.xxx.xxx
    [deviceEnablePrompt] =>
    [devicePrompt] => #
    [deviceUsername] => xxxxx
    [devicePassword] => xxxx
    [deviceEnablePassword] => xxxxxx
    [templateId] => 4
    [nodeCatId] => 1
)
8 October 2017 03:57:32 AM
show startup-configPHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1341383256 bytes) in /home/rconfig/classes/sshlib/Net/SSH2.php on line 2017

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1341383256 bytes) in /home/rconfig/classes/sshlib/Net/SSH2.php on line 2017

**Comment by rconfig** [comment]
unable to verify, device is not support or verified in 3.8.6

**Comment by vipp** [comment]
I am also having this issue with a Cisco 4507.

25 January 2018 08:58:26 PM
show ip access-listPHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 3485273047 bytes) in /home/rconfig/classes/sshlib/Net/SSH2.php on line 2017

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 3485273047 bytes) in /home/rconfig/classes/sshlib/Net/SSH2.php on line 2017
