### ISSUE TITLE
"Install Configuration Settings" does nothing...

### ISSUE THREAD

**Issue by rideekulous** [rconfig/rconfig#68]
The **Check Settings** seems to be working fine, but nothing happens at all when I click **Install Database**. I have tried Chrome 63, Firefox 57, Firefox ESR 52, IE 11, Edge 41.

-- Centos Version --
CentOS Linux release 7.4.1708 (Core)  **_!MINIMAL_**

-- Apache Version --
Server version: Apache/2.4.6 (CentOS)
Server built:   Oct 19 2017 20:39:16

-- PHP Version --
PHP 7.0.25 (cli) (built: Oct 29 2017 13:43:03) ( NTS )

-- MYSQL Version --
5.6.38

![image](https://user-images.githubusercontent.com/21090563/34014082-b9319ee2-e0ce-11e7-8efe-548877c75af3.png)

**Comment by rideekulous** [comment]
Installed gnome enviro with firefox and got the same thing on the rConfig VM itself.

![image](https://user-images.githubusercontent.com/21090563/34015833-95a26d7a-e0d4-11e7-851a-3b529be77344.png)

**Comment by rideekulous** [comment]
This is the result I get when I click **Install Database**, immediately after clicking **Check Settings**.

![image](https://user-images.githubusercontent.com/21090563/34022248-0b42932a-e0f3-11e7-8270-7b6ebff60a67.png)

**Comment by rconfig** [comment]
your MySQL password is wrong per the output

**Comment by rideekulous** [comment]
@rconfig how is it passing the **Check Settings** task if that is the case?

**Comment by rideekulous** [comment]
I created a new user with a password **without special characters** and the **Install Database** function worked.
