### ISSUE TITLE
Hardcoded directories? 

### ISSUE THREAD

**Issue by shairozan** [rconfig/rconfig#69]
Why does the application constantly look back towars /home/rconfig for installation? Not sure why this doesn't just read from the execution directory of the application.

**Comment by rconfig** [comment]
Because! 

Closing as this is neither a bug or an issue.

**Comment by shairozan** [comment]
Right, well thanks for the **absolutely useless** answer. I'll let you know when I've written your replacement.

**Comment by rconfig** [comment]
I'm sorry I upset you. You see my time is tight. I But look forward to positively contributing to your replacement @shairozan. If you decide to put 1000's of hours of work into it, and 50k+ lines of code, and decide to make it free and open source, that is :)

Thanks & regards
