### ISSUE TITLE
Description limitations on scheduled report task, 3.6 new install

### ISSUE THREAD

**Issue by bjh45964** [rconfig/rconfig#7]
When  saving a schedule for a report, the description appears to be stored as an integer.  Description must be numeric and can be as large as 2147483647.  If you try any alpha or 2147483648 you get a blank screen.  This is a fresh install of 3.6 on a fresh install of CentOS 7

**Comment by bjh45964** [comment]
Looks like changing $taskType to $_POST['taskType'] at lines 204 and 219 fixes this.  Not sure if there is anything more to this or just a simple mistake.

**Comment by mfrederickson** [comment]
It looks like there was possible a cut-and-paste and forget-to-rename problem on lines https://github.com/rconfig/rconfig/blob/master/www/lib/crud/scheduler.crud.php#L36 and https://github.com/rconfig/rconfig/blob/master/www/lib/crud/scheduler.crud.php#L43

**Comment by mfrederickson** [comment]
Looks like this might have been already addressed on the develop branch with this commit 197f8b16b07380c0440de2db4ae4248d7a11c05f

**Comment by rconfig** [comment]
@mfrederickson  thanks, your correct, this was fixed a few weeks back in the develop branch. I've merged to master, and will release 3.6.1 in the next week.
