### ISSUE TITLE
Unable to get output after upgrade to rconfig 3.8.7

### ISSUE THREAD

**Issue by jnizamj** [rconfig/rconfig#73]
Ive installed rconfig 3.5.7 earlier and it's working as expected.
Then I tried to upgrade to rconfig 3.8.7 and follow the steps in www.rconfig.com.

After done, it failed to capture the configuration at all. The directory /home/rconfig/data/... were successfully created but the files are empty:-

_[root@dory rconfig]# ll data/Switches/SHTMVLSP01/2018/Feb/07/
total 0
-r--r--r--. 1 apache apache **0** Feb  7 23:55 showcdpneigh-1555.txt
-r--r--r--. 1 apache apache **0** Feb  7 23:55 showipaccess-list-1555.txt
-r--r--r--. 1 apache apache **0** Feb  7 23:55 showstartup-config-1555.txt_

Even I tried to fresh install rconfig 3.8.7, the result is the same.

Did I missed out something during installation? 

Thanks a lot.

This is what I installed in the system:
CentOS 7 
PHP 7.0.27 (cli) (built: Jan  2 2018 12:38:03)
mysql  Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1
Apache/2.4.6 (CentOS)

**Comment by rconfig** [comment]
The fact you are getting files means rCOnfig is working. You need to follow these troubleshooting steps to see why rConfig is not getting data back from your devices.

Your issue is likely to be either;
1.	A credential issue
2.	A prompt configuration issue (has the correct device prompt been placed on the device config page in rConfig)
3.	Or other connectivity issue. KB2001 on the knowledge base @rconfig.com can help assist you.
4.	Please read help files and support documentation.

**Comment by jnizamj** [comment]
Hi,
This is the output when I run the debugging:-
Is this normal? because I still can get the output printed in the files. Please help... :-(

_Success: Connected to IPHZIPRT01 (x.x.x.x) for taskID 461434 - in (File: /home/rconfig/lib/showCmdScript.php)
7 February 2018 07:40:57 PM
show startup-configterminal length 0
IPHZIPRT01#\r\n------------------------------------------------------\r\n
IPHZIPRT01#7 February 2018 07:40:57 PM
Array
(
)
The owner permisions for directory /home/rconfig/data/ were reset to owner apache because script was run interactively_

**Comment by ayad99** [comment]
Hi

We had the same issue. I have checked all the points suggested here (and in kb2001) by rConfig team. But it simply does not work with Telnet. Interestingly I used another tool and it picked up the config dump fine using the same Telnet credentials. So this is not a device config issue, or device credential issue. And this is not a rConfig issue as the settings are pretty straight forward. SSH works fine though in rConfig. It seems like there is a hidden bug in rConfig. 

I understand that the rConfig tool is free, but the support is paid. But the way rConfig team is asking to buy support to identify this hidden issue appears bit unethical. It would have been better if rConfig was not offered as a free tool and rather had a paid subscription in the first place. At least we would all know what to expect.

**Comment by ayad99** [comment]
Hi @jnizamj 

It's strange to know that Telnet config was working in 3.5.7, but not working in the new version 3.8.7. Do you have the previous version 3.5.7? Can you please share with me or tell me where to download it from?

Thanks

**Comment by jnizamj** [comment]
Hi @ayad99 

It's good to know that not only me who facing this issue :-)
I had tried to figure out what was happened and still clueless. In fact that, the problem happen only on the template with "no-enable" command. 
Perhaps could you change your template to Cisco IOS - SSH - Enable and observe how it behave.

I do have version 3.5.7 in my hard drive. Can I have your e-mail address?
Thanks.

**Comment by rconfig** [comment]
I'm happy to do a live session with any or all of you to resolve, Please ping me privately to organise, and I will revert here with my findings. 
Stephen@rconfig.com
