### ISSUE TITLE
PHP Fatal error with snippets

### ISSUE THREAD

**Issue by s265925** [rconfig/rconfig#76]
Hi, You forgot to change/update Connection params in file lib/configCategoryScript.php (last commit)

Using snippet makes Fatal error
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Connection::__construct(), 21 passed in /var/www/rconfig/lib/configCategoryScript.php on line 150 and exactly 22 expected in /var/www/rconfig/classes/connection2.class.php:41

need to add 
                $templateparams['auth']['sshInteractive']

**Comment by rconfig** [comment]
oopps... fixed.. thanks
