### ISSUE TITLE
Error In Laravel Logs + 500 Server Error

### ISSUE THREAD

**Issue by SlodeSoft** [rconfig/rconfig#76]
In /var/www/html/rconfig/storage/logs/laravel-2023-09-16.log

Is it a error about Mail configuration.

i've got =

[2023-09-16 15:10:08] production.ERROR: Symfony\Component\Mime\Address::__construct(): Argument #1 ($address) must be of type string, null given, called in /v
ar/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Mail/Message.php on line 58 {"exception":"[object] (TypeError(code: 0): Symfony\\Component\\Mime\\
Address::__construct(): Argument #1 ($address) must be of type string, null given, called in /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Mai
l/Message.php on line 58 at /var/www/html/rconfig/vendor/symfony/mime/Address.php:42)

Another issue, it's not possible to connect on port 80.
The Web server return a 500 Server Error. How to view logs related to this problem ?

**Comment by stephenstack** [comment]
See information on troubleshooting 500 errors in the wiki ⬆️

https://github.com/rconfig/rconfig/wiki/How-to-Enable-app_debug-to-True-in-a-Laravel-App-for-Debugging-500-Errors

**Comment by SlodeSoft** [comment]
Thanks for you support @stephenstack , it was permissions file root:root in /var/www/html/rconfig/bootstrap/cache/

if you launch php artisan config:cache && php artisan rconfig:clear-all

The rights root:root are applied to this dir
