### ISSUE TITLE
where is writeSnippetTelnet() ?

### ISSUE THREAD

**Issue by s265925** [rconfig/rconfig#77]
Hi 
There is a problem when using snippet with telnet ! missing function ?
Looked for writeSnippetTelnet() in connection2.class.php and nothing there !
Here is error :+1: 
PHP Fatal error:  Uncaught Error: Call to undefined method Connection::writeSnippetTelnet() in /var/www/rconfig/lib/configCategoryScript.php:183

thanks !

**Comment by s265925** [comment]
Noticed two other things, please help !

in connectTelnet function : 
1 . this part seems to duplicate ! no need for this! since we check for username again! :   
`            if($this->_username){
                 if($this->_readTo($this->_userPrmpt) == true){
                    if($this->_linebreak == 'n'){$this->_send($this->_username . "\n");}
                    if($this->_linebreak == 'r'){$this->_send($this->_username . "\r");}
                }
            }   `

2. whe we check for empty user pass there is a 'if' i think it should change  : 

`        if(!empty($this->_send($this->_username))){ // check if username is not empty. Blank usernames & PWs are allow: do not check of username prompt if blank
` 
to 
`        if(!empty($this->_username)){ // check if username is not empty. Blank usernames & PWs are allow: do not check of username prompt if blank`

AND

`        if(!empty($this->_send($this->_password))){ // check if _password is not empty. Blank usernames & PWs are allow: do not check of _password prompt if blank`

to 

`        if(!empty($this->_password)){ // check if _password is not empty. Blank usernames & PWs are allow: do not check of _password prompt if blank`

**Comment by rconfig** [comment]
hi, first issue seems valid and I will resolve. The second issue is not. And appears that you may misunderstand the code. Best to separate them to different logged issues as well

**Comment by s265925** [comment]
OK i will open a new issue !

**Comment by rconfig** [comment]
resolved in upcoming release
