### ISSUE TITLE
Add Alias to Web Path

### ISSUE THREAD

**Issue by SlodeSoft** [rconfig/rconfig#77]
Hello, 

How to get web path as = 12.0.0.1/rconfig/login instead 127.0.0.1/login
in HTTPD config vhost Alias doesn't work.

in .env i specified https://myproxy.mydomain.com/rconfig, but i get redirect to root path /login.

**Comment by stephenstack** [comment]
Unclear why you would want to do this. If its for the purposes for a reverse proxy, this is not the scope of the issues list here. Sorry!

**Comment by SlodeSoft** [comment]
Add a subpath to the web access, or a prefixmiddleware if you prefer as in a python web environment.

**Comment by stephenstack** [comment]
This is not a supported rConfig setup, or hosting configuration. We can close this
