### ISSUE TITLE
problem with paging cmd?!

### ISSUE THREAD

**Issue by s265925** [rconfig/rconfig#78]
Hi,
In some devices , i.e (old Huawei SW) there is no "screen-length" or any other command to for making device to not page the output ! 
I see there is a pagerPrompt in templates defined ! maybe we can use it for paging ?

**Comment by rconfig** [comment]
Are you able to test on your devices and provide a working template? I can do it, but only under a support agreement

**Comment by s265925** [comment]
Yes , I am working with more than three brands , for Huawie devices it is needed to change the code also little change in connection class,
"system-view" in Huawie is equivalent to "config terminal" in Cisco
See :
http://forum.huawei.com/en/thread-82497-1-1.html

I also implemented the idea:
"wait for paging prompt" and sending "space" for  continue to get the output. then remove the paging prompts from the output.
