### ISSUE TITLE
Manual or schedul task download config failed

### ISSUE THREAD

**Issue by Rex1152** [rconfig/rconfig#78]
**Describe the bug**
Manual or schedul task download config failed
but click copy debug cli command download sucess
Horizon→Pending Jobs is queue than failed job
 Exception show 

`
/Illuminate\Queue\TimeoutExceededException: App\Jobs\DownloadConfigNow has timed out. in /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:798
Stack trace:
#0 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(217): Illuminate\Queue\Worker->timoutExceededException()
#1 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(253): Illuminate\Queue\Worker->Illuminate\Queue\{closure}()
#2 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#3 /var/www/html/rconfig/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1296): stream_select()
#4 /var/www/html/rconfig/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3458): phpseclib3\Net\SSH2::stream_select()
#5 /var/www/html/rconfig/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3980): phpseclib3\Net\SSH2->get_binary_packet()
#6 /var/www/html/rconfig/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3125): phpseclib3\Net\SSH2->get_channel_packet()
#7 /var/www/html/rconfig/app/Http/Controllers/Connections/SSH/SendCommand.php(93): phpseclib3\Net\SSH2->read()
#8 /var/www/html/rconfig/app/Http/Controllers/Connections/SSH/SendCommand.php(42): App\Http\Controllers\Connections\SSH\SendCommand->standardShowCommand()
#9 /var/www/html/rconfig/app/Http/Controllers/Connections/SSHConnectionManager.php(80): App\Http\Controllers\Connections\SSH\SendCommand->sendShowCommand()
#10 /var/www/html/rconfig/app/Http/Controllers/Connections/SSHConnectionManager.php(41): App\Http\Controllers\Connections\SSHConnectionManager->sendSSHCommand()
#11 /var/www/html/rconfig/app/Http/Controllers/Connections/MainConnectionManager.php(36): App\Http\Controllers\Connections\SSHConnectionManager->SSHConnectionAndOutput()
#12 /var/www/html/rconfig/app/CustomClasses/DeviceDownloadClass.php(52): App\Http\Controllers\Connections\MainConnectionManager->setupConnectAndReturnOutput()
#13 /var/www/html/rconfig/app/Console/Commands/rconfigDeviceDownload.php(46): App\CustomClasses\DeviceDownloadClass->downloadDevices()
#14 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\rconfigDeviceDownload->handle()
#15 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#17 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#18 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#19 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
#20 /var/www/html/rconfig/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#21 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\Component\Console\Command\Command->run()
#22 /var/www/html/rconfig/vendor/symfony/console/Application.php(1081): Illuminate\Console\Command->run()
#23 /var/www/html/rconfig/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#24 /var/www/html/rconfig/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#25 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Console/Application.php(162): Symfony\Component\Console\Application->run()
#26 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(400): Illuminate\Console\Application->call()
#27 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Illuminate\Foundation\Console\Kernel->call()
#28 /var/www/html/rconfig/app/Jobs/DownloadConfigNow.php(41): Illuminate\Support\Facades\Facade::__callStatic()
#29 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\DownloadConfigNow->handle()
#30 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#31 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#32 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#33 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#34 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#35 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#36 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#38 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\Bus\Dispatcher->dispatchNow()
#39 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#40 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\Pipeline\Pipeline->then()
#42 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#43 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#44 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\Queue\Jobs\Job->fire()
#45 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\Queue\Worker->process()
#46 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\Queue\Worker->runJob()
#47 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\Queue\Worker->daemon()
#48 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\Queue\Console\WorkCommand->runWorker()
#49 /var/www/html/rconfig/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\Queue\Console\WorkCommand->handle()
#50 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#51 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#52 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#53 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#54 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#55 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
#56 /var/www/html/rconfig/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#57 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\Component\Console\Command\Command->run()
#58 /var/www/html/rconfig/vendor/symfony/console/Application.php(1081): Illuminate\Console\Command->run()
#59 /var/www/html/rconfig/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#60 /var/www/html/rconfig/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#61 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#62 /var/www/html/rconfig/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#63 {main}
`

**To Reproduce**
1. Go to 'device'
2. Click on 'download now'
3. status started no any error or result

**rConfig Version Information (You can copy this from the rConfig dashboard):**
OS VERSION
Ubuntu 20.04.6 LTS
PHP / LARAVEL VERSION
8.2.10/10.22.0
REDIS VERSION
5.0.7
MYSQL VERSION
10.3.38

**Comment by stephenstack** [comment]
`/Illuminate\Queue\TimeoutExceededException: App\Jobs\DownloadConfigNow has timed out.`

This is normally associated with connectivity issues to the device. Follow the troubleshooting guide here, and see what the debug comes back with.  It would be useful to know the make/ model of the device also.

https://docs.rconfig.com/general/troubleshooting

**Comment by Rex1152** [comment]
before open this issues already read  troubleshooting guide
those devices on v3 is ok ,but v6 download failed
if this issues is about device why use debug cli command download sucess?

**Comment by stephenstack** [comment]
can you provide output from the debug command? Otherwise we can close the issue

**Comment by Rex1152** [comment]
> can you provide output from the debug command? Otherwise we can close the issue
Here is debug command output 

for safe I skip something information about config




root@rconfig:/var/www/html/rconfig# cd /var/www/html/rconfig && php artisan rconfig:download-device 71 -d
Start rconfig:download-device IDs:71
""" // app/Http/Controllers/Connections/SSHConnectionManager.php:71
<-\r\n
00000000  53:53:48:2d:32:2e:30:2d:43:69:73:63:6f:2d:31:2e  SSH-2.0-Cisco-1.\r\n
00000010  32:35:0a                                         25.\r\n
\r\n
->\r\n
                                              .\r\n
\r\n
-> NET_SSH2_MSG_KEXINIT (since last: 0.0255, network: 0s)\r\n

\r\n
<- NET_SSH2_MSG_KEXINIT (since last: 0.0044, network: 0.0044s)\r\n

\r\n
-> NET_SSH2_MSG_KEXDH_GEX_REQUEST (since last: 0.0015, network: 0s)\r\n
00000000  00:00:06:00:00:00:08:00:00:00:10:00              ............\r\n
\r\n
<- NET_SSH2_MSG_KEXDH_GEX_GROUP (since last: 0.0013, network: 0.0013s)\r\n
                  ..........\r\n
\r\n
-> NET_SSH2_MSG_KEXDH_GEX_INIT (since last: 0.0084, network: 0s)\r\n
                                  .,P.g\r\n
\r\n
<- NET_SSH2_MSG_KEXDH_GEX_REPLY (since last: 0.405, network: 0.405s)\r\n
                  ...\r\n
\r\n
-> NET_SSH2_MSG_NEWKEYS (since last: 0.0015, network: 0s)\r\n
                                                 \r\n
\r\n
<- NET_SSH2_MSG_NEWKEYS (since last: 0, network: 0s)\r\n
                                                 \r\n
\r\n
-> NET_SSH2_MSG_SERVICE_REQUEST (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth\r\n
\r\n
<- NET_SSH2_MSG_SERVICE_ACCEPT (since last: 0.1987, network: 0.1986s)\r\n
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth\r\n
\r\n
-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0001, network: 0s)\r\n
00000000  00:00:00:03:63:69:62:00:00:00:0e:73:73:68:2d:63  ....cib....ssh-c\r\n
00000010  6f:6e:6e:65:63:74:69:6f:6e:00:00:00:04:6e:6f:6e  onnection....non\r\n
00000020  65                                               e\r\n
\r\n
<- NET_SSH2_MSG_USERAUTH_FAILURE (since last: 0.0017, network: 0.0017s)\r\n
.\r\n
\r\n
-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0001, network: 0s)\r\n

\r\n
<- NET_SSH2_MSG_USERAUTH_SUCCESS (since last: 0.0027, network: 0.0027s)\r\n
                                                 \r\n
\r\n
-> NET_SSH2_MSG_CHANNEL_OPEN (since last: 0.0001, network: 0s)\r\n
00000000  00:00:00:07:73:65:73:73:69:6f:6e:00:00:00:02:7f  ....session.....\r\n
00000010  ff:ff:ff:00:00:40:00                             .....@.\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION (since last: 0.0016, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:03:00:00:20:00:00:00:10:00  .......... .....\r\n
\r\n
-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0001, network: 0s)\r\n
00000000  00:00:00:03:00:00:00:07:70:74:79:2d:72:65:71:01  ........pty-req.\r\n
00000010  00:00:00:05:76:74:31:30:30:00:00:00:a0:00:00:08  ....vt100.......\r\n
00000020  00:00:00:00:00:00:00:00:00:00:00:00:01:00        ..............\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0.0016, network: 0s)\r\n
00000000  00:00:00:02                                      ....\r\n
\r\n
-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0001, network: 0s)\r\n
00000000  00:00:00:03:00:00:00:05:73:68:65:6c:6c:01        ........shell.\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0.0015, network: 0s)\r\n
00000000  00:00:00:02                                      ....\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.001, network: 0s)\r\n
#\r\n
\r\n
-> NET_SSH2_MSG_CHANNEL_DATA (since last: 30.0124, network: 0s)\r\n
00000000  00:00:00:03:00:00:00:12:74:65:72:6d:69:6e:61:6c  ........terminal\r\n
00000010  20:6c:65:6e:67:74:68:20:30:0a                     length 0.\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 1.0003, network: 0.0001s)\r\n
00000000  00:00:00:02:00:00:00:01:74                       ........t\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:65                       ........e\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:72                       ........r\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6d                       ........m\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:69                       ........i\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6e                       ........n\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:61                       ........a\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6c                       ........l\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:20                       ........ \r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6c                       ........l\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:65                       ........e\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6e                       ........n\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:67                       ........g\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:74                       ........t\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:68                       ........h\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:20                       ........ \r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:30                       ........0\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:02:0d:0a                    ..........\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)\r\n
#\r\n
\r\n
-> NET_SSH2_MSG_CHANNEL_DATA (since last: 30.0235, network: 0s)\r\n
00000000  00:00:00:03:00:00:00:09:73:68:6f:77:20:72:75:6e  ........show run\r\n
00000010  0d                                               .\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0031, network: 0.0001s)\r\n
00000000  00:00:00:02:00:00:00:01:73                       ........s\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:68                       ........h\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6f                       ........o\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0008, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:77                       ........w\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0009, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:20                       ........ \r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0013, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:72                       ........r\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0009, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:75                       ........u\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6e                       ........n\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:02:0d:0a                    ..........\r\n
\r\n

\r\n
-> NET_SSH2_MSG_CHANNEL_DATA (since last: 29.5389, network: 0s)\r\n
00000000  00:00:00:03:00:00:00:0d:73:68:6f:77:20:76:65:72  ........show ver\r\n
00000010  73:69:6f:6e:0d                                   sion.\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0024, network: 0.0001s)\r\n
00000000  00:00:00:02:00:00:00:01:73                       ........s\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:68                       ........h\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6f                       ........o\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0008, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:77                       ........w\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0009, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:20                       ........ \r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:76                       ........v\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:65                       ........e\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0017, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:72                       ........r\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0005, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:73                       ........s\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:69                       ........i\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0008, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6f                       ........o\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0008, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6e                       ........n\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0005, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:02:0d:0a                    ..........\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0081, network: 0.0017s)\r\n
#\r\n
\r\n
-> NET_SSH2_MSG_CHANNEL_DATA (since last: 30.0139, network: 0.0001s)\r\n
00000000  00:00:00:03:00:00:00:0e:73:68:6f:77:20:69:70:20  ........show ip \r\n
00000010  72:6f:75:74:65:0d                                route.\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.054, network: 0.0001s)\r\n
00000000  00:00:00:02:00:00:00:01:73                       ........s\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0003, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:68                       ........h\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6f                       ........o\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0009, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:77                       ........w\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0009, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:20                       ........ \r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:69                       ........i\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0003, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:70                       ........p\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0009, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:20                       ........ \r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0009, network: 0.0001s)\r\n
00000000  00:00:00:02:00:00:00:01:72                       ........r\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6f                       ........o\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0008, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:75                       ........u\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.001, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:74                       ........t\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:65                       ........e\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:02:0d:0a                    ..........\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0397, network: 0.0001s)\r\n
\r\n
-> NET_SSH2_MSG_CHANNEL_DATA (since last: 29.9192, network: 0.0001s)\r\n
00000000  00:00:00:03:00:00:00:0c:73:68:6f:77:20:63:64:6f  ........show cdp\r\n
00000010  20:6e:65:0d                                       ne.\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0036, network: 0.0001s)\r\n
00000000  00:00:00:02:00:00:00:01:73                       ........s\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:68                       ........h\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0006, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6f                       ........o\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0007, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:77                       ........w\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:20                       ........ \r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0003, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:63                       ........c\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0003, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:64                       ........d\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0012, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6f                       ........o\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0011, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:20                       ........ \r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6e                       ........n\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0012, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:65                       ........e\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:02:0d:0a                    ..........\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0037, network: 0s)\r\n
\r\n
\r\n
-> NET_SSH2_MSG_CHANNEL_DATA (since last: 30.0165, network: 0.0001s)\r\n
00000000  00:00:00:03:00:00:00:0d:73:68:6f:77:20:76:6c:61  ........show vla\r\n
00000010  6e:20:62:72:0d                                   n br.\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0084, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:73                       ........s\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:68                       ........h\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.001, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6f                       ........o\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:77                       ........w\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:20                       ........ \r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:76                       ........v\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.001, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6c                       ........l\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0011, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:61                       ........a\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:6e                       ........n\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0008, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:20                       ........ \r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0009, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:62                       ........b\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:01:72                       ........r\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:02:0d:0a                    ..........\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0063, network: 0.0003s)\r\n
\r\n
"""
Start device download for  ID:71
Config downloaded for 4G-LTE-SW01 with command: "show run" was successful
Config downloaded for 4G-LTE-SW01 with command: "show version" was successful
Config downloaded for 4G-LTE-SW01 with command: "show ip route" was successful
Config downloaded for 4G-LTE-SW01 with command: "show cdp ne" was successful
Config downloaded for 4G-LTE-SW01 with command: "show vlan br" was successful
End rconfig:download-device
root@rconfig:/var/www/html/rconfig#
