### ISSUE TITLE
Unable to clone

### ISSUE THREAD

**Issue by samir1955** [rconfig/rconfig#79]
root@rconfig-rconfig:/var/www/html# git clone https://github.com/rconfig/rconfig.git
Cloning into 'rconfig'...
fatal: unable to access 'https://github.com/rconfig/rconfig.git/': gnutls_handshake() failed: Error in the pull function.

**Comment by stephenstack** [comment]
You need to google that one, its a TLS or other connectivity issue between your server and Github.
