### ISSUE TITLE
LDAP & rconfig ?

### ISSUE THREAD

**Issue by sam5558** [rconfig/rconfig#79]
Hello everybody,
first of all, rconfig is an interesting project for those who want to move from rancid to new and maintained solution.

I just have a question, is it possible to login on rconfig using LDAP users ?
If not, is there any way to implement LDAP with rconfig ? (workaround on php for ex.)  

Thanks

**Comment by webmastir** [comment]
> I just have a question, is it possible to login on rconfig using LDAP users ?

Yes. 
[https://www.google.com/search?q=rConfig+LDAP](https://www.google.com/search?q=rConfig+LDAP)

**Comment by sam5558** [comment]
Hello @webmastir, 

In https://www.rconfig.com/blog/62-releasing-v35, the rConfig team are talking about LDAP integration for version 4, we're still in 3.8.7 ....
Also, i'm unable any trace of LDAP neither in my sandbox nor in the rConfig demo gui.
Maybe if it's possible to connect using LDAP you can explain to me how @webmastir .
Thanks

**Comment by rconfig** [comment]
Correct, LDAP integration will not be available in 3.x. I am working on a new 4.x version currently. This is still a few months away

**Comment by webmastir** [comment]
Oops, I worded my reply wrong, @sam5558. My apologies. I meant "yes, it is coming", which the Owner just confirmed.
