### ISSUE TITLE
Can't add new user

### ISSUE THREAD

**Issue by bjh45964** [rconfig/rconfig#8]
When trying to add a new user, I put in all required fields and click save, and I get:

["600"]

from page http://x.x.x.x/lib/ajaxHandlers/ajaxGetPageTimeout.php?error

New user is not saved.

Fresh install of 3.6 on fresh install of CentOS 7

**Comment by mfrederickson** [comment]
The "600" is the page timeout value from the settings table.  The same thing happened to me in my development environment, but when I used the menu to go back to Users, I saw that it did indeed add the user.

**Comment by bjh45964** [comment]
I tried Safari, IE and Firefox and none of them saved the user in my case.  The “600” is the only thing on the page, so to get back to the menu I have to re-browse to the root of the site or hit the back button which returns to the filled in form.  Navigating to the user list from that point still yields no new user.

**Comment by mfrederickson** [comment]
I suspect it has to do with redirections-- I'm looking at the network tab under the developer tools...  I'll try on our server in a little bit...

**Comment by mfrederickson** [comment]
Looks like the global `$session`'s referrer is being overwritten to ajaxGetPageTimeout.php.  When I comment that ajax call out of pageTimeout.js, the user add works as expected.  Something for @rconfig to look into...
