### ISSUE TITLE
Connection Template for Alcatel Lucent ?

### ISSUE THREAD

**Issue by sam5558** [rconfig/rconfig#80]
Hello everyone,
Just asking, have someone managed to add Alcatel Lucent equipements to rConfig, maybe by using a custom Connection Template ? 

It may also be interesting to add it to the existing device connection templates.

**Comment by rconfig** [comment]
agreed, you can attempt to create your own. Or you can pay for support and we can create one for you

**Comment by rconfig** [comment]
nothing further on this
