### ISSUE TITLE
System returns HTML server error 500

### ISSUE THREAD

**Issue by TOAOQ** [rconfig/rconfig#80]
Hi,

After a few months of not using the rconfig server I started again. At first all looked OK but no backups were made, and no devices were shown when trying to open that menu.
Then performed upgrade as per instructions: https://github.com/rconfig/rconfig#updating
After a reboot of the server I got the mentioned 500 | Server Error

Can anyone help me with some pointers to check what's happened?

Thanks in advance!

**Comment by stephenstack** [comment]
See the wiki here https://github.com/rconfig/rconfig/wiki/How-to-Enable-app_debug-to-True-in-a-Laravel-App-for-Debugging-500-Errors

Let us know what error is returned

**Comment by TOAOQ** [comment]
Hi Stephen,

This is returned after enabling the debug:
[A screenshot of a computer  Description automatically generated]

Somehow the application encryption key went missing?!
Will search on how to solve this, but help is appreciated!

Thanks in advance!

Best regards,
Q


From: Stephen Stack ***@***.***>
Date: Wednesday, 27 September 2023 at 12:24
To: rconfig/rconfig ***@***.***>
Cc: TOAOQ ***@***.***>, Author ***@***.***>
Subject: Re: [rconfig/rconfig] System returns HTML server error 500 (Issue #80)

See the wiki here https://github.com/rconfig/rconfig/wiki/How-to-Enable-app_debug-to-True-in-a-Laravel-App-for-Debugging-500-Errors<https://www.google.com/url?q=https://github.com/rconfig/rconfig/wiki/How-to-Enable-app_debug-to-True-in-a-Laravel-App-for-Debugging-500-Errors&source=gmail-imap&ust=1696415046000000&usg=AOvVaw2GJXnmHY3LgnTWwOrwPCiK>

Let us know what error is returned

**Comment by TOAOQ** [comment]
Hej again,

Solving the key was easy: solution was provided in the screenshot haha: php artisan key:generate
Got the webgui back up but still cannot see any devices. On the dashboard it states I have a devicecount of 9, but when opening that page I get an error about invalid MAC:

[A screenshot of a computer  Description automatically generated]

and in Laravel Horizon I see this error:

[A screenshot of a computer  Description automatically generated]

Also rebooted the server after the previous steps but still the same error.
Any ideas anyone?

Best regards,

Q
From: Q TC ***@***.***>
Date: Friday, 29 September 2023 at 10:31
To: rconfig/rconfig ***@***.***>, rconfig/rconfig ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [rconfig/rconfig] System returns HTML server error 500 (Issue #80)
Hi Stephen,

This is returned after enabling the debug:
[A screenshot of a computer  Description automatically generated]

Somehow the application encryption key went missing?!
Will search on how to solve this, but help is appreciated!

Thanks in advance!

Best regards,
Q



From: Stephen Stack ***@***.***>
Date: Wednesday, 27 September 2023 at 12:24
To: rconfig/rconfig ***@***.***>
Cc: TOAOQ ***@***.***>, Author ***@***.***>
Subject: Re: [rconfig/rconfig] System returns HTML server error 500 (Issue #80)

See the wiki here https://github.com/rconfig/rconfig/wiki/How-to-Enable-app_debug-to-True-in-a-Laravel-App-for-Debugging-500-Errors<https://www.google.com/url?q=https://github.com/rconfig/rconfig/wiki/How-to-Enable-app_debug-to-True-in-a-Laravel-App-for-Debugging-500-Errors&source=gmail-imap&ust=1696415046000000&usg=AOvVaw2GJXnmHY3LgnTWwOrwPCiK>

Let us know what error is returned

**Comment by stephenstack** [comment]
So, the application key encrypts passwords in the DB. When the key is lost or changes, the new key cannot decrypt the PWs so you get a ' invalid MAC' error. You have a few choices to get things back working. 1) restore the old key. But this might be permenantly lost. So the second option is to manually delete the passwords in the DB and recreate them in the GUI. 
Edit the DB, and delete the device passwords in the 'devices' table. If there is a password in the settings table for smtp delete that too (just null-ify the passwords fields, the rest of the record can stay intact). Then back in to the UI and open the devices, and re-enter the PWs. That should resolve it.

**Comment by TOAOQ** [comment]
Thanks!

Lucky for me I have only 9 devices to look after 😊
Will search and learn on how to alter the DB (and gain some DB knowledge)

Best regards,

Q


From: Stephen Stack ***@***.***>
Date: Friday, 29 September 2023 at 11:09
To: rconfig/rconfig ***@***.***>
Cc: TOAOQ ***@***.***>, Author ***@***.***>
Subject: Re: [rconfig/rconfig] System returns HTML server error 500 (Issue #80)

So, the application key encrypts passwords in the DB. When the key is lost or changes, the new key cannot decrypt the PWs so you get a ' invalid MAC' error. You have a few choices to get things back working. 1) restore the old key. But this might be permenantly lost. So the second option is to manually delete the passwords in the DB and recreate them in the GUI.
Edit the DB, and delete the device passwords in the 'devices' table. If there is a password in the settings table for smtp delete that too (just null-ify the passwords fields, the rest of the record can stay intact). Then back in to the UI and open the devices, and re-enter the PWs. That should resolve it.

**Comment by stephenstack** [comment]
Login to the DB from the CLI. 
`mysql -u root -p`

show the DBs
`show databases;`

select your DB
`use rconfig;`


update the columns

`UPDATE devices
SET device_password = NULL;
UPDATE devices
SET device_enable_password = NULL;`

**Comment by TOAOQ** [comment]
Thanks fort he quick answer.

I was doen tot he last line on updating the columns and tried to figure out how to do it when you replied.
Just did that line and see the devices again. Will update the passwords now.

Any way I can copy the missing encryption key for safeguarding?

Best regards,

Q

From: Stephen Stack ***@***.***>
Date: Friday, 29 September 2023 at 12:02
To: rconfig/rconfig ***@***.***>
Cc: TOAOQ ***@***.***>, Author ***@***.***>
Subject: Re: [rconfig/rconfig] System returns HTML server error 500 (Issue #80)

Login to the DB from the CLI.
mysql -u root -p

show the DBs
show databases;

select your DB
use rconfig;

update the columns

UPDATE devices SET device_password = NULL; UPDATE devices SET device_enable_password = NULL;

**Comment by stephenstack** [comment]
A backup of the .env file specifically will help, but a backup of the entire app/ data and database is always a good idea, and the .env file is stored in the root of the rconfig app. /var/www/html/rconfig.

ok to close?

**Comment by TOAOQ** [comment]
Hi, sorry for the late reply. It is OK to close (wanted to check over the weekend how it held)

Will create a backup of the .env indeed, good advice.
Noticed just one minor (for me) thing: I am not able to create regular users, only admins?

**Comment by stephenstack** [comment]
Thanks, we'll resolve that user issue shortly with a PR
