### ISSUE TITLE
Default node Password in Device settings bug

### ISSUE THREAD

**Issue by sam5558** [rconfig/rconfig#81]
Hello,

In the settings section, I noticed that when we put in the Default node password a string containing a "+" character, when we click on update credentials the "+" sign will disappear from the password typed. eg : 
"StQfR_+By7k" [will transform to] "StQfR_ By7k"

**Comment by sam5558** [comment]
Hello,
Looks like the + sign is interpreted as a part of HTTP post so here's the workaround i found to make it work : 
Replace + by it's code %2B , so in the last example i gave it's gonna be StQfR__%2B_By7k instead of "StQfR_+By7k"

**Comment by rconfig** [comment]
thanks, will test this uout and add a fix if needed... appreciate the contribution

**Comment by rconfig** [comment]
closing this for now. Working on a new code release, and will expect this to be resolved in V4
