### ISSUE TITLE
Connect to devices using hostname and custom port

### ISSUE THREAD

**Issue by pitah81** [rconfig/rconfig#82]
I would like to be able to use hostname instead of IP address to connect to devices, as some devices are access using dyndns address due to IP addresses being dynamically assigned.

Also, it would be nice to be able to choose custom connection port in main device view, instead of having to create different templates to be able to backup configuration on devices accessible through non standard port.

It would also be nice if there was an option under each device to temporary disable backup of that device, instead of having to remove the device from the schedule.

OS VERSION
Rocky  9.2 (Blue Onyx)
PHP / LARAVEL VERSION
8.2.11 / 10.22.0
REDIS VERSION
6.2.7
MYSQL VERSION
10.5.16

**Comment by rconfig** [comment]
Acknowledged, we like these ideas and we agree with implementing them. We will add to our backlog, and feedback when a PR is completed.

**Comment by rconfig** [comment]
Resolved via pr #86 Would like to get feedback asap. Closing this for now, please create new issues if needed
