### ISSUE TITLE
[Fixed] Compare in Scheduled Tasks not working 

### ISSUE THREAD

**Issue by sam5558** [rconfig/rconfig#83]
Hello,

Whenever trying to use the compare feature in rConfig, nothing happened in the logs. 
When i executed my script via cli :  
`php /home/rconfig/lib/compareReportScript.php 677761`
I had an error in line 8.

It appears that @rconfig  miswritten the location of the php connection name, it should be `require("/home/rconfig/classes/connection2.class.php");` instead of `require("/home/rconfig/classes/connection.class.php");`

This fixes the issue for me, hopes @rconfig corrects it asap.
Cheers

**Comment by rconfig** [comment]
thank you @sam5558 I will test and incorporate to the next release.

**Comment by rconfig** [comment]
resolved in todays release.
