### ISSUE TITLE
chmod()

### ISSUE THREAD

**Issue by GC-53** [rconfig/rconfig#83]
Hi,
I have an issue with two switches that i can't seem to figure out on my own.
It concerns a Dell switch and a Cisco switch, different templates (default or slightly modified) - no obvious similarities.
The error i get is below.
The config is effectively downloaded from the switch, i assume the error lies somewhere at the point of copying the content or moving it... something something, no clue really ;)
Appreciate the help!

sh: 1: Syntax error: "(" unexpected
In FileOperations.php line 105:
  chmod(): No such file or directory

Tried manually running it with different permissions (root, www-data), tried chmod'ing the directory to 777 to rule out permission issues -> to no avail.
Other Dell or Cisco switches work fine (same templates).
Manually running 'show config' looks the same output as with other switches.

**Comment by stephenstack** [comment]
Hi

Can you share the content of In FileOperations.php line 105? and the block of code surrounding it. I have checked and the code looks good. Wondering if it was edited for changed for some reason

**Comment by GC-53** [comment]
Hi Stephen, thanks for picking this up.
Below is the code block you requested.
What strikes me odd is that the same code/templates do work perfectly for other switches, must not be the code then - or code in combination with certain output...

`        
// if'' to create the filename based on the command if not created & chmod to 666
        if (!file_exists($fullpath)) {
            exec('touch ' . $fullpath);
            chmod($fullpath, 0666);
        }

        return (string) $fullpath;
    }
/**
     * Function insertFileContents
     *
     * @param  string  $lines Command output from device
     * @param  string  $fullpath Fullpath as return by createFile Function to main script
     */
    private function _insertFileContents($lines, $fullpath)
    {
        // if the file is alread in place chmod it to 666 before writing info
        @chmod($fullpath, 0666); // disabled errors in case ops is not permitted
        // dump array into file & chmod back to RO
        $filehandle = fopen($fullpath, 'w+');
        file_put_contents($fullpath, $lines);
        fclose($filehandle);
        @chmod($fullpath, 0444); // disabled errors in case ops is not permitted
    }
`

For the sake of completeness, this is the last few lines from the output using the debug code:
`<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.1768, network: 0.0001s)\r\n
00000000  00:00:00:02:00:00:00:0c:44:42:2d:43:4f:52:45:2d  ........DB-CORE-\r\n
00000010  57:41:4e:23                                      WAN#\r\n
\r\n
"""
`

**Comment by stephenstack** [comment]
Agree its a bit odd. Might be something in the $fullpath interpreted incorrectly. The $fullpath is a combination of the path and a truncated version of the actual command. What commands are configured for these devices?

**Comment by GC-53** [comment]
The command used is simply 'show run', which manually does what i expect it to do...

I picked this up from laravel, but not much the wiser:

`[2023-10-16 11:30:55] production.ERROR: chmod(): No such file or directory {"exception":"[object] (ErrorException(code: 0): chmod(): No such file or directory at /var/www/html/rconfig/app/CustomClasses/FileOperations.php:105)
[stacktrace]
#0 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/rconfig/app/CustomClasses/FileOperations.php(105): chmod()
#3 /var/www/html/rconfig/app/CustomClasses/FileOperations.php(54): App\\CustomClasses\\FileOperations->createFile()
#4 /var/www/html/rconfig/app/CustomClasses/SaveConfigsToDiskAndDb.php(45): App\\CustomClasses\\FileOperations->saveFile()
#5 /var/www/html/rconfig/app/CustomClasses/DeviceDownloadClass.php(81): App\\CustomClasses\\SaveConfigsToDiskAndDb->saveConfigs()
#6 /var/www/html/rconfig/app/Console/Commands/rconfigDeviceDownload.php(46): App\\CustomClasses\\DeviceDownloadClass->downloadDevices()
#7 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\rconfigDeviceDownload->handle()
#8 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#12 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\\Container\\Container->call()
#13 /var/www/html/rconfig/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#14 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Console/Command.php(177): Symfony\\Component\\Console\\Command\\Command->run()
#15 /var/www/html/rconfig/vendor/symfony/console/Application.php(1040): Illuminate\\Console\\Command->run()
#16 /var/www/html/rconfig/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#17 /var/www/html/rconfig/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#18 /var/www/html/rconfig/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(200): Symfony\\Component\\Console\\Application->run()
#19 /var/www/html/rconfig/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#20 {main}
"}
`

Can i see anywhere what the full path is?
Running the debug command to text doesn't seem to show what path it tries to use...

**Comment by GC-53** [comment]
Well, guess it was right in my face afterall...
Both switches had "(stack)" in the name, hence the mention of unexpected "(".
Didn't realize that would be an issue as it accepted my naming input :)
My bad!
thanks for your time!

**Comment by stephenstack** [comment]
You mean, this was set in the Device Name field on the form. Yes, that would cause it. We will add validation to prevent this in future. Thanks

**Comment by GC-53** [comment]
exactly.
It only struck me after staring at it for 5 minutes :)

**Comment by rconfig** [comment]
closed resolved
