### ISSUE TITLE
Installation error at Apache/supervisor step -- Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by m0l3ch** [rconfig/rconfig#84]
**Describe the bug**
  I'm following the steps in this video: <https://www.youtube.com/watch?v=igyWHReBVYM> to install on Ubuntu 22.04.3 LTS, after completing OS setup and all install steps up to "8. Install supervisor", when I run the "./setup_supervisor.sh" command I get this error:

  unix:///var/run/supervisor.sock no such file

I then run supervisorctl status and get this error:

  horizon                          FATAL     Exited too quickly (process log may have details)

**To Reproduce**
1. Follow all setup instructions (documentation and video) to setup Ubuntu 22.04 OS and install rconfig up to step 8 of install
2. Run "chmod +x setup_supervisor.sh"
3. Run "./setup_supervisor.sh"
4. Get error "unix:///var/run/supervisor.sock no such file"

**Expected behavior**
  No error, and "supervisorctl status" command should return "RUNNING" output

**Screenshots**
  N/A

**rConfig Version Information (You can copy this from the rConfig dashboard):**

  No dashboard available at this point of install.

OS VERSION
  Ubuntu 22.04.3 LTS
PHP / LARAVEL VERSION
  8.2.11 / 10.22.0
REDIS VERSION
  6.0.16
MYSQL VERSION
  mysql  Ver 15.1 Distrib 10.6.12-MariaDB

**Logs info (can be retrieved from /var/www/html/rconfig6/storage/logs - try to paste relevant logs only)
  Only horizon and laravel logs found, error not found in either

**Additional context**
  None at this time

**Comment by rconfig** [comment]
Can you follow the steps in the new wiki article and see what results you get.

https://github.com/rconfig/rconfig/wiki/Supervisor-Error-%E2%80%90-unix:---var-run-supervisor.sock-no-such-file

**Comment by m0l3ch** [comment]
Output of "systemctl status supervisor":

● supervisor.service - Supervisor process control system for UNIX
     Loaded: loaded (/lib/systemd/system/supervisor.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-10-18 00:40:21 UTC; 16h ago
       Docs: http://supervisord.org
   Main PID: 2161 (supervisord)
      Tasks: 1 (limit: 4558)
     Memory: 17.3M
        CPU: 22.693s
     CGroup: /system.slice/supervisor.service
             └─2161 /usr/bin/python3 /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf

Oct 18 00:41:52 AM-rConfig supervisord[2161]: 2023-10-18 00:41:52,795 INFO exited: horizon (exit status 1; not expected)
Oct 18 00:41:53 AM-rConfig supervisord[2161]: 2023-10-18 00:41:53,798 INFO spawned: 'horizon' with pid 2386
Oct 18 00:41:54 AM-rConfig supervisord[2161]: 2023-10-18 00:41:54,035 INFO exited: horizon (exit status 1; not expected)
Oct 18 00:41:55 AM-rConfig supervisord[2161]: 2023-10-18 00:41:55,039 INFO spawned: 'horizon' with pid 2391
Oct 18 00:41:55 AM-rConfig supervisord[2161]: 2023-10-18 00:41:55,258 INFO exited: horizon (exit status 1; not expected)
Oct 18 00:41:57 AM-rConfig supervisord[2161]: 2023-10-18 00:41:57,263 INFO spawned: 'horizon' with pid 2396
Oct 18 00:41:57 AM-rConfig supervisord[2161]: 2023-10-18 00:41:57,500 INFO exited: horizon (exit status 1; not expected)
Oct 18 00:42:00 AM-rConfig supervisord[2161]: 2023-10-18 00:42:00,505 INFO spawned: 'horizon' with pid 2401
Oct 18 00:42:00 AM-rConfig supervisord[2161]: 2023-10-18 00:42:00,731 INFO exited: horizon (exit status 1; not expected)
Oct 18 00:42:01 AM-rConfig supervisord[2161]: 2023-10-18 00:42:01,733 INFO gave up: horizon entered FATAL state, too many start retries too quickly



###


Output of "php artisan horizon":

In Connection.php line 801:
                                                                                                                                                                                                                                                    
  SQLSTATE[HY000] [1045] Access denied for user 'rconfig'@'localhost' (using password: YES) (Connection: mysql, SQL: select * from information_schema.tables where table_schema = rconfig and table_name = settings and table_type = 'BASE TABLE')  
                                                                                                                                                                                                                                                    

In Connector.php line 65:
                                                                                             
  SQLSTATE[HY000] [1045] Access denied for user 'rconfig'@'localhost' (using password: YES)



###


Here's exactly what I used when defining the DB user (redacting the password):

CREATE USER 'rconfig'@'localhost' IDENTIFIED BY '[redacted]';
GRANT ALL PRIVILEGES ON rconfig.* TO 'rconfig'@'localhost';
FLUSH PRIVILEGES;

**Comment by stephenstack** [comment]
Your password must be incorrect. Maybe reset the mysql password, update the .env file with the new one and try again. This needs to be correct to proceed.

**Comment by rconfig** [comment]
This is likely resolved, so closing for now, thanks
