### ISSUE TITLE
Huawei OLT EA5800X2 [backup script]

### ISSUE THREAD

**Issue by Rajeevtamang** [rconfig/rconfig#88]
Hello there, 
I am using Huawei devices the template you provide is working fine with my router and switches but its not working with my OLT.  I guess its cuz of parameter that device ask when i type "display current-config /save-config" 
 "OLT-2>enable 
  OLT-2#display current-configuration 
{ <cr>|include-default<K>|interface<K>|ont<K>|port<K>|section<K>|service-port<K>||<K> }: 

  Command:
          display current-configuration
[Active: H901MPSAE; Standby: H901MPSAE]
"

as i need to press the "ENTER key twice to  get the output.

---TEMPLATE  USED---

main:
  name: "Huawei VRP SSH no enable"
  desc: "Huawei VRP SSH based connection without enable mode"
connect:

  #connection timeout in seconds
  timeout: 5

  #type either telnet or ssh - must be in lowercase
  protocol: ssh

  #type port number for connection protocol choose from 1 - 65535
  port: 22
auth:
  #Set username name prompt. Must be in quotes. If left blank, username will not be sent.
  username: ""
  #Set password name prompt. Must be in quotes
  password: ""

  #Set enable mode on or off
  enable: off

  #set enable mode command. Must be in quotes
  enableCmd: "enable"

  #set enable mode password prompt. Must be in quotes
  enablePassPrmpt: ""

  #set HP 'press any key' status. Is 'on' or 'off'
  hpAnyKeyStatus: on
 #set HP 'press any key' prompt.
  hpAnyKeyPrmpt: "Press any key to continue"
config:

  #Experimental: Some vendors use different linebreak settings. Choose 'n' (default) or 'r'
  linebreak: "n"

  #Disable config scrolling/ paging command. on/off
  paging: on

  #Disable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
  pagingCmd: "scroll"
  #re-enable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
  resetPagingCmd: "undo scroll"

  #Set pager prompt. Must place command in quotations
  pagerPrompt: "--- More ---"

  #Set pager prompt key-stroke. Must place command in quotations
  pagerPromptCmd: ""

  #Save configuration command. Leave blank, or set as required. Must be in quotes
  saveConfig: "save"

  #Set exit command. Must place command in quotations
  exitCmd: "quit"
  
  --
  I would really appreciated if i you could suggest/help me to solve the issue.
  
  ALSO,
  in switch/router where "Warning: The initial password poses security risks.
The password needs to be changed. Change now? [Y/N]:n
Info: The max number of VTY users is 21, the number of current VTY users online is 1, and total number of terminal users online is 1.
" this is enable i can not fetch the config.

**Comment by stephenstack** [comment]
Hi,

Sorry for the delay in response, we are working hard on V7 pro. Was this ever resolved?

You could try 
display current-configuration \n include-default \n y

BUt i would not have a lot of confidence this would work. One thing I can say, in V7 pro, we have a beta of Bring your own Code. Becuase we came across this similar issue in Radware devices, which is very odd CLI implementations, we have developed a feature which allows us to develop Expect or python ( or other scripts) to interact with these types of CLIs. ping us at info@rconfig.com for more information. 

best,
