### ISSUE TITLE
HPE comware 

### ISSUE THREAD

**Issue by aguro90** [rconfig/rconfig#91]
Good day,

In order to add compatibility with more devices , could it be another option for certain HP devices to enable xtd-cli-mode? There is options for other methods like HPAnyKeyStatus but in my case is asking for type "y"(model HPE_OfficeConnect_1950) and i think most code its done ;)

**Comment by stephenstack** [comment]
Hi, sorry for the delay, we are working hard on a V7 Pro release. I dont think we would support this directly. Its barely supported by HP as its a command to give extended developer access, but you could try placing the command in the pagingCmd section of the template, or chain commands using a \n in the pagingCmd section.

**Comment by aguro90** [comment]
Xdxxxrxxx

**Comment by aguro90** [comment]
Xx
