### ISSUE TITLE
Scheduled Tasks Not Running

### ISSUE THREAD

**Issue by njarbeau** [rconfig/rconfig#95]
**Describe the bug**
I've performed a fresh install of rconfig on a new server and onboarded some devices to it.  However, when I setup a scheduled task to backup the configurations, it does not automatically run.  The task will run if I manually start it. 

**Screenshots**

![image](https://github.com/rconfig/rconfig/assets/155185696/fc9c96ee-f56f-4958-bb7a-686d9cf7faf3)

**rConfig Version Information (You can copy this from the rConfig dashboard):**
OS VERSION
Ubuntu 22.04.3 LTS
PHP / LARAVEL VERSION
8.2.11 / 10.22.0
REDIS VERSION
6.0.16
MYSQL VERSION
10.6.12

**Comment by stephenstack** [comment]
If you open the Queue manager from the Settings menu. what is the status of Horizon?
Also, what is the output of Cron? 'crontab -l ' for root?

**Comment by njarbeau** [comment]
The status of Horizon is "Active".  

The output of crontab -l for root is:
"no crontab for root"

**Comment by stephenstack** [comment]
The installer may not have completed successfully for you. Add this line to cron for the scheduler to work

* * * * * cd /var/www/html/rconfig && php artisan schedule:run >> /dev/null 2>&1

**Comment by njarbeau** [comment]
That worked.  Thank you.
