### ISSUE TITLE
Hp switch backups

### ISSUE THREAD

**Issue by ousturali** [rconfig/rconfig#96]
hello team,

i appreciate the good work in your software ; really good stuff.
I installed it in my company , and try to test it with Hp swithces,
ı can successfully add them ,but cannot got the backups , the output is limited to only 20 lines or similar stuff, 
Is there anyway to bypass that

thanks

**Comment by stephenstack** [comment]
Hi

Can you read this thread, and see if the steps in there help you?
https://github.com/rconfig/rconfig/issues/92

**Comment by ousturali** [comment]
Hi stephenstack

thanks for leading me the correctly, solved the problem by chanicing the template and replaced the "linebreak " with "r" as mentinoed in the template, (my fault since i didnt carefully readed befor)

Thanks for all your efforts in this software, i really liked it 👍

**Comment by stephenstack** [comment]
Happy days... you bet! 👍
