### ISSUE TITLE
phpseclib3\Exception\UnableToConnectException

### ISSUE THREAD

**Issue by antoinechauvn** [rconfig/rconfig#99]
**Describe the bug**
When trying to connect to F5 device, it throws timeout error.

**Expected behavior**
Connecting to F5 device

**Screenshots**
![image](https://github.com/rconfig/rconfig/assets/83721477/daa7a21d-b903-4748-b84e-b0e6059647c4)

**rConfig Version Information (You can copy this from the rConfig dashboard):**
OS VERSION
Red Hat Enterprise 8.8 (Ootpa)
PHP / LARAVEL VERSION
8.2.12 / 10.32.1
REDIS VERSION
5.0.3
MYSQL VERSION
10.3.39

**Logs info (can be retrieved from /var/www/html/rconfig6/storage/logs - try to paste relevant logs only)**

**Additional context**
The ssh command is working on the device. This is important to consider (So no blocking on the firewall side)

**Comment by stephenstack** [comment]
As I understand, this issue was resolved. Marking it closed. 

Thanks
